### ISSUE TITLE
Restore da base dengue (arquivo latest_dengue.sql)

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#120]
@flavioamieiro 

Quando fui fazer o restore da base dengue saiu uma mensagem de erro:

```
ERROR:  could not create unique index "Clima_cemaden_pk"
DETAIL:  Key (id)=(29132438) is duplicated.
```

não sei se é algo que tem algum impacto, porém achei melhor reportar.

**Comment by flavioamieiro** [comment]
@xmnlab Eu ainda preciso baixar e reimportar o banco aqui no meu ambiente pra ver se consigo reproduzir, mas nunca encontrei esse bug antes. Isso não deveria acontecer, já que existe essa constraint no banco.

O resto da importação funcionou sem problemas?

**Comment by xmnlab** [comment]
Sim, o resto funcionou normal :)

**Comment by flavioamieiro** [comment]
@xmnlab Fiz um dump novo do banco (de hoje), baixei e restaurei aqui no meu computador. Não tive esse mesmo problema. Se você quiser, testa com esse dump novo. Pode ser que o problema não exista mais nele mesmo (além disso, ele está com os dados atualizados).

**Comment by xmnlab** [comment]
perfeito! vou testar! agradecido!


El 4 sept. 2017 12:56, "Flávio Amieiro" <notifications@github.com> escribió:

@xmnlab <https://github.com/xmnlab> Fiz um dump novo do banco (de hoje),
baixei e restaurei aqui no meu computador. Não tive esse mesmo problema. Se
você quiser, testa com esse dump novo. Pode ser que o problema não exista
mais nele mesmo (além disso, ele está com os dados atualizados).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AlertaDengue/AlertaDengue/issues/120#issuecomment-327001968>,
or mute the thread

**Comment by xmnlab** [comment]
funcionou! obrigado!
