### ISSUE TITLE
Password fixa em map.py

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#121]
@flavioamieiro 

Neste arquivo o password está fixo

https://github.com/AlertaDengue/AlertaDengue/blob/master/AlertaDengue/dados/maps.py

acredito que posso trocar por PSQL_PASSWORD

correto?

**Comment by flavioamieiro** [comment]
@xmnlab Sim! Obrigado por ter corrigido isso! Esse arquivo ainda é usado regularmente?

**Comment by xmnlab** [comment]
@flavioamieiro  na verdade eu não tenho ideia .. preciso conferir no código ... mas como dá erro aqui pra mim, creio que é usado.

**Comment by xmnlab** [comment]
correção já está em produção.
