### ISSUE TITLE
AttributeError: module 'chunked_upload.models' has no attribute 'generate_filename'

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#122]
@flavioamieiro 

você já viu esse problema?

```
  File "/AlertaDengue/AlertaDengue/dbf/migrations/0002_dbfchunkedupload.py", line 24, in Migration
    ('file', models.FileField(max_length=255, upload_to=chunked_upload.models.generate_filename)),
AttributeError: module 'chunked_upload.models' has no attribute 'generate_filename'
```
acredito que seja problema de versão

**Comment by flavioamieiro** [comment]
@xmnlab nunca encontrei esse erro, nem aqui no meu ambiente, nem com os dockers. Confesso que tem um tempo que não faço um deploy do projeto, então concordo que pode ser um problema de versão.

Aqui no meu ambiente estou usando o django 1.11 e o chunked_upload 1.0. Quais versões estão aí?

**Comment by flavioamieiro** [comment]
@xmnlab criei um novo virtualenv pra testar aqui e encontrei o mesmo problema na hora de rodar os testes. As versões são parecidas o suficiente (1.11.4 e 1.0) para o problema não dever ser esse (mas é claro que ainda não descarto a possibilidade).

Vou tentar descobrir o que é e corrigir.

**Comment by flavioamieiro** [comment]
@xmnlab o commit 2b6aceb que já está no develop corrige o erro.

A migração que cria as tabelas pro modelo estava fazendo referência a uma função que parece não existir no código do chunked_upload há um tempo. Minha suspeita é que ela foi criada com uma versão anterior da biblioteca (onde essa função existia) e a referência ficou no código da migração. Quando rodamos qualquer comando de managemente (test ou runserver, por exemplo) num ambiente que não tinha as migrações aplicadas, ele esbarrou nesse erro.

Me avise por favor se isso corrige o problema pra você também.

**Comment by xmnlab** [comment]
resolvido!
