### ISSUE TITLE
Criação de canal de comunicação rápida

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#125]
Acho que talvez a utilização de um canal de comunicação rápida de grupo, nos ajudaria a melhorar a comunicação referente ao projeto. Algo como telegram, gitter, slack ...

O que vocês pensam a respeito?

**Comment by Dinidiniz** [comment]
Eu acredito que telegram ou whatsapp para o alerta dengue seria bem beneficial!

**Comment by xmnlab** [comment]
bacana! acho q o telegram seria bem interessante .. porque pode manter o histórico ...

**Comment by xmnlab** [comment]
@flavioamieiro @fccoelho 

o que vocês acham da ideia de criar um canal no telegram pra esse projeto?

**Comment by flavioamieiro** [comment]
@xmnlab eu confesso que não uso muito o telegram. Principalmente quando estou trabalhando, tento me manter longe do celular pra conseguir me concentrar. 
Mas não tenho nada contra a ideia de criar um canal lá não, de jeito nenhum. Meu usuário lá é o mesmo que aqui no github.

**Comment by xmnlab** [comment]
@flavioamieiro 

você acha que o gitter seria mais conveniente?

**Comment by flavioamieiro** [comment]
Eu nem conhecia o gitter, então acho que não seria exatamente mais conveniente. Mas a questão toda é que eu gosto de reduzir as notificações enquanto trabalho pra evitar distrações (a unica exceção é o e-mail, que já uso praticamente só pra trabalho). 

De qualquer jeito, eu acho que o telegram pode ser sim uma boa ideia. Só não acho que vou estar disponível lá muito mais do que por e-mail, mas entendo que a comunicação é diferente nos dois canais, o que pode ser um bom motivo pra criar esse outro espaço.

**Comment by xmnlab** [comment]
Feito! https://t.me/alerta_dengue_br

**Comment by xmnlab** [comment]
done
