### ISSUE TITLE
Trocar de python3-memcached para python-memcached

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#127]
@flavioamieiro 

vou tentar fazer a troca do python3-memcached para python-memcached

o python3-memcached era um port do python-memcached para python3, mas agora o python-memcached já funciona no python3 e o python3-memcached ficou obsoleto [1].

https://github.com/eguven/python3-memcached/blob/master/README#L1

**Comment by flavioamieiro** [comment]
Ótimo @xmnlab
