### ISSUE TITLE
gráfico de casos estimados errado para o MRJ

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#134]
na página do muncipio do rio de Janeiro, a curva de casos estimados está igual à de casos (ver últimas semanas, onde deveriam ser diferentes).

Como estes erros não ocorrem no relatório da cidade, o erro deve ser da construção do gráfico no site.

**Comment by xmnlab** [comment]
@fccoelho 

Fazendo uma consulta diretamente na base de dados:

```sql

SELECT 
  data, 
  SUM(casos), 
  SUM(casos_est), 
  SUM(casos_estmin), 
  SUM(casos_estmax) 
FROM "Municipio"."alerta_mrj" 
GROUP BY data
ORDER BY data DESC
LIMIT 12
```

Da esse resultado:

|DATA|CASOS|CASOS-ESTIMADOS|CASOS-EST-MIN|CASOS-EST-MAX|
|:-|:-|:-|:-|:-|
|2017-08-20|6|6|6|6|
|2017-08-13|18|18|18|18|
|2017-08-06|25|25|25|25|
|2017-07-30|33|33|33|33|
|2017-07-23|29|29|29|29|
|2017-07-16|37|37|37|37|
|2017-07-09|28|28|28|28|
|2017-07-02|30|30|30|30|
|2017-06-25|31|31|31|31|
|2017-06-18|33|33|33|33|
|2017-06-11|42|42|42|42|
|2017-06-04|67|67|67|67|

E é o mesmo resultado que aparece no site.

**Comment by fccoelho** [comment]
Ok vou ver com a @claudiacodeco como ela está fazendo a atualização desta
tabela.

Em 18 de set de 2017 19:09, "Ivan" <notifications@github.com> escreveu:

**Comment by xmnlab** [comment]
@fccoelho

alguma novidade sobre esse item?

**Comment by fccoelho** [comment]
Aparentemente  há um bug no sistema de calculo dos casos_est só para a a cidade do rio

vamos corrigir e o problema vai desaparecer naturalmente.

**Comment by xmnlab** [comment]
ok!
