### ISSUE TITLE
HistoricoView

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#142]
@fccoelho, @flavioamieiro 

Vocês sabem se o HistoricoView ainda é utilizado?

Eu não vi link para ele. E se você digita a url [1], retorna um erro:

-> AttributeError: 'DataFrame' object has no attribute 'cor'

Se não for mais utilizado, já tiro ele do código.

[1] https://info.dengue.mat.br/historico/

**Comment by fccoelho** [comment]
Não  é usado mais não...

Em 3 de out de 2017 19:10, "Ivan" <notifications@github.com> escreveu:

**Comment by flavioamieiro** [comment]
Obrigado @xmnlab !
