### ISSUE TITLE
Mudança de dj-static para whitenoise

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#145]
@flavioamieiro 

Estava falando com o mantenedor do pacote dj-static para anaconda e este me comentou que ele mesmo já não está quase usando o dj-static e que agora passou a usar o whitenoise [1]

não sei se é melhor .. mas talvez seria uma boa dar uma olhada no projeto.

**vou abrir essa issue, mas já vou fechá-la .. apenas para deixar o registro disso.

[1] http://whitenoise.evans.io/en/stable/

**Comment by flavioamieiro** [comment]
@xmnlab legal! Não conheço o whitenoise. Vou dar uma olhada melhor depois.
