### ISSUE TITLE
[EE] Erro de acesso a página de cidade.

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#148]
@flavioamieiro 

as páginas das cidades estão com erro 500.

me poderias colocar para receber as mensagens de erro?

**Comment by flavioamieiro** [comment]
@xmnlab eu te adicionei na lista de admins do ambiente de produção também. Você deve passar a receber e-mails a partir de agora.

O erro que estava acontecendo agora era:

```
ProgrammingError at /alerta/4106902/dengue
(psycopg2.ProgrammingError) relation "forecast.forecast_cases" does not exist
LINE 6:           forecast.forecast_cases AS f
                  ^
 [SQL: "\n        SELECT \n          TO_CHAR(MIN(init_date_epiweek), 'YYYY-MM-DD') AS epiweek_min,\n          TO_CHAR(MAX(init_date_epiweek), 'YYYY-MM-DD') AS epiweek_max\n        FROM \n          forecast.forecast_cases AS f\n          INNER JOIN forecast.forecast_city AS fc\n            ON (f.geocode = fc.geocode AND fc.active=TRUE)\n          INNER JOIN forecast.forecast_model AS fm\n            ON (fc.forecast_model_id = fm.id AND fm.active = TRUE)\n        WHERE f.geocode=4106902 AND cid10='A90'\n        "]
```

Por algum motivo as duas migrações que existem para a app forecast estavam marcadas como aplicadas, mas as tabelas não existiam no banco. Quando eu executei o `python manage.py migrate` ele dizia o seguinte:

```
Operations to perform:                                                                                                                                                   
  Apply all migrations: admin, auth, contenttypes, dbf, forecast, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

Como esse banco está naquela situação que já discutimos e as migrações são em sql, eu apliquei elas manualmente no banco de produção. Isso fez as páginas das cidades voltarem a funcionar (pelo que pude ver, pelo menos).

Uma coisa que temos que ver, é que realmente existem mudanças nos models que não estão nas migrações. Se rodarmos um `python manage.py makemigrations` ele cria dois arquivos de migração: um pra app `dbf` (por causa da mudança do campo `upload_to`) e outro pra app `forecasts`, adicionando campos no modelo e alterando alguns.

No caso da app `dbf`, como eu conhecia o modelo e sei que a migração criada não vai causar nenhum problema, eu incluí a nova migração e fiz um deploy. A migração nova pra app `forecast` eu não incluí por que não conheço bem o modelo e nem as mudanças depois que as migrações originais foram criadas, então eu prefiro que você avalie elas. Criei a issue #149 para isso.
