### ISSUE TITLE
Incluir migrações pendentes para app `forecast`

### ISSUE THREAD

**Issue by flavioamieiro** [AlertaDengue/AlertaDengue#149]
Como descrevi na issue #148, algumas migrações estão pendentes para essa app.

O resultado quando criamos as migrações com o `makemigrations` é o seguinte:

```python
# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dados', '__first__'),
        ('forecast', '0002_create_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiweek', models.IntegerField(help_text='Semana epidemiológica')),
                ('published_date', models.DateField(db_column='published_date', help_text='Data da publicação da previsão')),
                ('init_date_epiweek', models.DateField(db_column='init_date_epiweek', help_text='Data do inicio da semana da previsão')),
                ('cases', models.IntegerField(help_text='Casos Previstos')),
                ('cid10', models.ForeignKey(db_column='cid10', help_text='Doença', on_delete=django.db.models.deletion.CASCADE, to='dados.CID10')),
                ('city', models.ForeignKey(db_column='geocode', help_text='Cidade', on_delete=django.db.models.deletion.CASCADE, to='dados.City')),
            ],
            options={
                'db_table': 'forecast"."forecast_cases',
                'verbose_name_plural': 'forecast',
            },
        ),
        migrations.CreateModel(
            name='ForecastCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Está Ativo?')),
                ('city', models.ForeignKey(db_column='geocode', help_text='Código do Município', on_delete=django.db.models.deletion.CASCADE, to='dados.City')),
            ],
            options={
                'db_table': 'forecast"."forecast_city',
                'verbose_name_plural': 'forecast cities',
            },
        ),
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do Modelo de Previsão', max_length=128)),
                ('weeks', models.IntegerField(help_text='Total de Semanas')),
                ('commit_id', models.CharField(help_text='ID do commit (github)', max_length=7)),
                ('active', models.BooleanField(help_text='Está ativo?')),
            ],
            options={
                'db_table': 'forecast"."forecast_model',
            },
        ),
        migrations.AddField(
            model_name='forecastcity',
            name='forecast_model',
            field=models.ForeignKey(db_column='forecast_model_id', help_text='Modelo de Previsão', on_delete=django.db.models.deletion.CASCADE, to='forecast.ForecastModel'),
        ),
        migrations.AddField(
            model_name='forecastcases',
            name='forecast_model',
            field=models.ForeignKey(db_column='forecast_model_id', help_text='Modelo de Previsão', on_delete=django.db.models.deletion.CASCADE, to='forecast.ForecastModel'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastcity',
            unique_together=set([('city', 'forecast_model')]),
        ),
        migrations.AlterUniqueTogether(
            name='forecastcases',
            unique_together=set([('epiweek', 'city', 'cid10', 'forecast_model', 'published_date')]),
        ),
    ]
```

@xmnlab você pode, por favor, avaliar se essas mudanças são realmente necessárias e não vão criar problemas com a aplicação?

**Comment by xmnlab** [comment]
eu também estou se acesso ao admin ... se puderem também criar um usuario e senha pra mim ... assim verifico também como está o cadastro lá.

**Comment by flavioamieiro** [comment]
@xmnlab como eu descrevi no [meu comentário na issue original](https://github.com/AlertaDengue/AlertaDengue/issues/148#issuecomment-344216551), eu já rodei o sql na mão. A questão é que, mesmo depois disso ele acusa que ainda tem migrações não criadas. Isso pode ser por que, com as migrações sendo SQL, ele não entende completamente que aqueles campos já estão no estado certo (eu acho que ele entende que alguns dos campos ele reconhece, por que a migração que ele gera tem algumas alterações de campos nela). Acho que a chave pro problema (assumindo que o esquema atual esteja condizente com o modelo) está no jeito que ele introspecta o modelo e compara com o que está no banco.

Sobre o admin: criei seu usuário lá e mandei os detalhes por e-mail.

**Comment by xmnlab** [comment]
@flavioamieiro

Entendi ... Pode ser tb q o makemigrate nao ta reconhecendo o schema
correto ...

**Comment by flavioamieiro** [comment]
@xmnlab exatamente. Mas o que eu não tinha certeza é se o que está nessa migração (em SQL) representa realmente a última versão do modelo. Sendo esse o caso, temos só que silenciar o alarme falso no migrate.

Eu tô lendo a documentação pra ver se tem algum jeito de "avisar" pro makemigrate que aquelas mudanças já estão contempladas (sem de fato executar as mudanças).

Se isso não for possível, talvez seja o caso de desligarmos migrações para essa app, e fazer elas na mão (mantendo os scripts no diretório `sql/`).

Ainda é estranho que esse SQL não tenha sido executado quando rodamos o migrate no processo de deploy, mas eu não consegui debugar isso no ambiente de desenvolvimento.

**Comment by xmnlab** [comment]
@flavioamieiro 

se colocamos o sql na pasta sql .. ele é executado quando é executado os tests?

**Comment by flavioamieiro** [comment]
@xmnlab não. Eu tinha me esquecido que isso seria um problema. Temos que encontrar mesmo um jeito de fazer o sistema de migrações entender que essa migração atende o modelo então.

**Comment by xmnlab** [comment]
ok!

vou tentar também pensar em alguma coisa ...

**Comment by flavioamieiro** [comment]
Uma coisa que eu pensei é que poderia ser que a migração está ignorando o namespace "forecast".  

Eu olhei o [models.py](https://github.com/AlertaDengue/AlertaDengue/blob/master/AlertaDengue/forecast/models.py#L42) e achei estranho o jeito que as aspas estão no db_name ('forecast"."forecast_city', com aspas duplas só no meio). De início achei que isso poderia ser o problema, mas aí eu percebi que o código está funcionando assim (com as tabelas tendo sido criadas manualmente no namespace certo), então não acho que seja isso. 

Mas será que isso pode estar causando problemas nas migrações?

**Comment by xmnlab** [comment]
se não me engano no django ele faz algo assim:

```python

sql = '''
select * from "%(db_table)s"
''' % db_table

# então para incluir o schema é preciso fazer
db_table = 'forecast"."forecast_city'

```

isso é uma gambiarra na verdade porque o django não suporta schema :S

porém, talvez só com o set_path já apontando para esse esquema já funcionaria ... 
por algum motivo aqui não tinha funcionado (talvez na criação das tabelas no test) .. 
mas posso tentar outra vez :)

ref:

https://stackoverflow.com/questions/1160598/how-to-use-schemas-in-django

> Mas será que isso pode estar causando problemas nas migrações?

eu ainda acho que é uma soma disso com o database router :( ... mas ainda não vi uma forma melhor de fazer isso :(

**Comment by flavioamieiro** [comment]
@xmnlab acho que entendi o problema. Pra isso não acontecer, a gente tem que "anotar" o `RunSQL` com o estado em que aquele `RunSQL` vai deixar o modelo. Eu vi isso na [documentação dessa classe RunSQL](https://docs.djangoproject.com/en/1.11/ref/migration-operations/#special-operations). O atributo responsável é o `state_operations`

Eu estou restaurando o banco (o que demora um bocado) pra testar se isso funciona. Se funcionar, faço um pull request com o patch pra ver se resolve.

**Comment by xmnlab** [comment]
@flavioamieiro

uau!! que bacana! obrigado Flavio!

**Comment by flavioamieiro** [comment]
@xmnlab não foi tão simples quanto parecia. Abri o pull request #150, mas não estou tão certo de que é uma boa solução. Quando puder, dá uma olhada no meu comentário lá e vê o que você acha.

**Comment by xmnlab** [comment]
@flavioamieiro

Imagino .. Ok ... Daqui a pouco já começo a ver isso :)
