### ISSUE TITLE
Definir armazenamento das imagens no Servidor

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#152]
As imagens que estão sendo capturadas pelo @Dinidiniz precisarão ser guardadas em um diretório fixo (ou melhor: arvore de diretórios) no servidor. 

@flavioamieiro qual o diretório que você recomenda?
Como as imagens representam várias variáveis ao longo do tempo: temperatura, chuva, etc. precisaríam estar armazenadas em diretórios separados, mas comum nomenclatura controlada para acesso.

Uma vez definido o local de armazenamento podemos iniciar a cópia das imagens já baixadas e passar para a automatização da captura que deverá ficar no AlertaDengueCaptura (abrirei uma nova Issue para isso)

**Comment by xmnlab** [comment]
@fccoelho @flavioamieiro 

aqui para os notebooks eu criei um diretório na raiz do sistema chamado tiffs.

para os diretórios de cada tipo de imagem, poderia ser a raiz do nome do arquivo, tudo em minusculo. 
ex: para `LST_Day_1km_2017_11_04.tif` poderia ser lst_day_1k ...

**Comment by xmnlab** [comment]
poderíamos também jogar esses arquivos num repositório separada e dentro do servidor apenas sincronizar.

**Comment by flavioamieiro** [comment]
A princípio, o ideal seria ter esse diretório configurável. Como no AlertaDengueCaptura e aqui nós usamos o [decouple](https://github.com/henriquebastos/python-decouple) para manter as configurações, podemos só pegar essa variável e definir o diretório certo em cada ambiente.

Para o deploy do ambiente de produção, vamos provavelmente definir um volume do docker, [como já fazemos para outros diretórios que precisam estar disponíveis para a aplicação](https://github.com/AlertaDengue/AlertaDengue/blob/master/docker-compose.yml#L36). 

Acho que pra resolvermos isso, precisamos primeiro fechar a AlertaDengue/AlertaDengueCaptura#30 .

**Comment by flavioamieiro** [comment]
Sobre as imagens já baixadas, podemos deixar elas em qualquer diretório dentro de `/Storage/` no servidor, por enquanto. Depois eu posso mover para outro lugar, se for necessário (e depois que os ajustes na [outra issue](AlertaDengue/AlertaDengueCaptura#30) forem feitos).

**Comment by xmnlab** [comment]
@flavioamieiro 
acho que essa issue já pode ser fechada, já que já temos a definição da estrutura: https://github.com/AlertaDengue/AlertaDengue/blob/develop/README_MAPSERVER.md

e a definição dos diretórios que estão já sendo usados pelo Docker do mapserver.

o que opinas?

**Comment by flavioamieiro** [comment]
@xmnlab concordo. Com a #162 encerramos isso.
