### ISSUE TITLE
Documentação Mapserver

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#164]
# Objetivos / Objectivos / Purpose
Guia para usuário que deseja consumir os serviços oferecidos via Mapserver

## Geral / General

* Objetivo da solicitação / Objectivo de la solicutud / Purpose of the request

Facilitar o uso pelos analistas no projeto

## Específicos / Specific

* Funcionalidades [desejadas / deseadas] / Desired functionalities

Tutorial em Markdown ou Jupyter ou ambos detalhando o consumo dos mapas

**Comment by xmnlab** [comment]
@fccoelho 

creio que iremos necessitar preparar uma tela ou uma lista com os links para acessar o serviço do mapserver.

na url vai alguns campos como hbox e width e height que, se não informado corretamente, pode alterar muito o resultado.

**Comment by xmnlab** [comment]
@fccoelho 

aqui está a primeira versão do documento: https://github.com/xmnlab/AlertaDengue/blob/develop/notebooks/MapServer-DOC.ipynb

sería bom mais detalhes do que se espera desse documento para deixá-lo completo.

**Comment by fccoelho** [comment]
Concordo, podemos compor uma página com informações técnicas sobre o acesso
tanto ao maps ever quanto à API

Talvez fique bom embaixo de uma entrada de menu chamada "serviços públicos
de dados"

Em 29 de jan de 2018 21:41, "Ivan" <notifications@github.com> escreveu:

**Comment by xmnlab** [comment]
ok .. vou trabalhar nisso!

**Comment by xmnlab** [comment]
progresso da atividade: issue contemplada em #171
