### ISSUE TITLE
Atualizar bootstrap para versão 4

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#168]
# Objetivos / Objectivos / Purpose
 
## Geral / General

* Objetivo da solicitação / Objectivo de la solicutud / Purpose of the request
  * Atualizar e migrar o sistema para usar a versão 4 do bootstrap (https://getbootstrap.com/docs/4.0/migration/)

## Específicos / Specific

* Funcionalidades [desejadas / deseadas] / Desired functionalities
  * Atualizar biblioteca bootstrap para versão 4;
  * atualizar código para funcionar com a versão 4 do bootstrap;

# Justificativa / Justification

* Problemas que se pretende resolver / Problems that are to be solved
  * a versão 4 do bootstrap possui algumas características que ajudarão na melhoria da interface, como por exemplo, classes de cards e decks;

# Entradas / Input

* [Dados / Datos] de entrada / Input data
* Origem / Origen / Source 
* Formatos / Input format
* Significado de cada atributo / Meaning of each attribute

não aplica

# Saídas / Salidas / Output

* Dados de saída / Datos de salida / Output data
* Destino / Destiny
* Formatos / Output format
* Onde e como os dados serão apresentados / Dónde y cómo los datos serán presentados / When and how data will be presented

não aplica

# Processamento / Procesamiento / Processing

* Fluxo de trabalho / Flujo de trabajo / Workflow

não aplica

**Comment by xmnlab** [comment]
progresso da atividade: já foi trocada a lib django-bootstrap3 django-bootstrap4 .. falta apenas algumas páginas para fazer os ajustes.

**Comment by xmnlab** [comment]
Para a issue #167, tive que atualizar umas libs js ... então por isso já aproveitei e fiz o merge do branch issue167 com o issue168 ...

**Comment by fccoelho** [comment]
Ótimo!

Em sáb, 7 de abr de 2018 13:01, Ivan <notifications@github.com> escreveu:
