### ISSUE TITLE
BUG: Séries de chikungunya para o CE não aparecem

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#176]
nós temos dados de chikungunia para o estado do Ceará, mas as séries não aparecem quando selecionadas, somenta a da dengue. testei para o município de maracanaú

**Comment by xmnlab** [comment]
@fccoelho 

pelo que vi aqui .. essa consulta utiliza a Historico_alerta ... e na base de dados de duas semanas atrás não temos nenhum dado pra essa cidade.

SQL utilizado:

```
select * from "Municipio"."Historico_alerta_chik"
where municipio_geocodigo = 2307650
```

**Comment by fccoelho** [comment]
então vai depender da @claudia-codeco  preparar estas tabelas, ou pelo menos para as outras doenças temos que utilizar a tabela notificações

```sql
SELECT ano_notif,se_notif,cid10_codigo,municipio_geocodigo 
from "Municipio"."Notificacao" WHERE municipio_geocodigo=2307650 and ano_notif>=2017 
order by se_notif, cid10_codigo;
```

**Comment by xmnlab** [comment]
Creio que melhor seria esperar a atualização da tabela historico_alerta já que também impacta no novo módulo de relatórios

**Comment by fccoelho** [comment]
então vai depender da @claudia-codeco  preparar estas tabelas, ou pelo menos para as outras doenças temos que utilizar a tabela notificações

```sql
SELECT ano_notif,se_notif,cid10_codigo,municipio_geocodigo 
from "Municipio"."Notificacao" WHERE municipio_geocodigo=2307650 and ano_notif>=2017 
order by se_notif, cid10_codigo;
```

**Comment by claudia-codeco** [comment]
Atualmente só estamos rodando alerta de chikungunia em Fortaleza. Vou resolver isso.

**Comment by xmnlab** [comment]
agradecido @claudia-codeco  :)

**Comment by claudia-codeco** [comment]
@xmnlab @fccoelho 

A tabela historico alerta chik está atualizada

**Comment by xmnlab** [comment]
ótimo! o gráfico já aparece!
na tela inicial também já aparece os 184 municipios participantes para o
estado CE!

2018-04-04 9:45 GMT-04:00 Claudia Codeço <notifications@github.com>:

**Comment by xmnlab** [comment]
os outros dados do card do CE na tela inicial ainda mostra 0 .. talvez falte atualizar as views ... 

@flavioamieiro as views são atualizadas uma vez por dia?

**Comment by fccoelho** [comment]
Acho que talvez a atualização das views para chik precisem ser adicionadas
ao CRONTAB


@claudia-codeco, vai fazer o da Zika também no CE?

2018-04-04 11:13 GMT-03:00 Ivan <notifications@github.com>:

**Comment by xmnlab** [comment]
@fccoelho @flavioamieiro 

qual é a periodicidade de atualização das informações no banco de dados?

na página inicial está mostrando que a última atualização foi 25 de Março de 2018.

**Comment by fccoelho** [comment]
Semanal

Em qui, 5 de abr de 2018 23:06, Ivan <notifications@github.com> escreveu:

**Comment by xmnlab** [comment]
já podemos fechar essa issue?

**Comment by fccoelho** [comment]
Acho que sim

Em sáb, 7 de abr de 2018 12:59, Ivan <notifications@github.com> escreveu:
