### ISSUE TITLE
Replace text within box 'Want to report a breeding site?'

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#179]
# Objetivos / Objectivos / Purpose
Corrigir a informação no box que fica no pé da página da page de municipios, que atualmente só é verdadeira para a cidade do Rio de Janeiro.

## Específicos / Specific

* Funcionalidades [desejadas / deseadas] / Desired functionalities
Tornar a informação de denuncia de criadouros específica para cada estado.

- Nos municípios do RJ: "'contacte a central de apoio ao cidadão: 1746"
- Nos municípios do ES: o texto é : "contacte a secretaria de saúde de sua cidade"
- Para os municípios do PR, o texto é: "contacte a secretaria de saúde da sua cidade" e coloque o link para
http://www.dengue.pr.gov.br/modules/conteudo/conteudo.php?conteudo=19
- Para os municipios do CE: "contacte a central de apoio ao cidadão: 0800.285.0880 
- Para municípios de MG e SP: contacte a secretaria de saúde de sua cidade"

**Comment by eltonn** [comment]
Vou analisar essa issue

**Comment by esloch** [comment]
This issues was resolved by PR #204
