### ISSUE TITLE
Melhorar Inteface de API Para leigos

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#184]
# Objetivos / Objectivos / Purpose

Melhorar a usabilidade do acesso aos dados do infodengue para não programadores, criando uma interface com caixa de texto semelhante ao do servidor de mapas, para gerar uma tabela csv servido pela API usando datatables.

por enquanto, continuar permitindo apenas uma tabela por municipio de cada vez.

Futuramente, permitir que selecione um estado inteiro e gere uma tabela resumo a nivel de estado ou regional de saude

## Geral / General

* Objetivo da solicitação / Objectivo de la solicutud / Purpose of the request

## Específicos / Specific

* Funcionalidades [desejadas / deseadas] / Desired functionalities

- [x] incluir na tabela servida, uma coluna com numero acumulado de casos no ano, 
- [x] incluir formulário para realização da consulta a API.
- [x] alterar a API para aceitar a informação de ano inicio e ano final da consulta. 
- [x] atualizar documentação

# Justificativa / Justification

* Problemas que se pretende resolver / Problems that are to be solved

# Entradas / Input

* [Dados / Datos] de entrada / Input data

No formulário deverá conter:

- geocode: código IBGE da cidade
- disease: tipo de doença a ser consultado (str:dengue|chikungunya|zika)
- format: formato de saída dos dados (str:json|csv)
- ew_start: semana epidemiológica de início da consulta (int:1-53)
- ey_start: ano de inicio da consulta (int: 2010-9999)
- ew_end: semana epidemiológica de final da consulta (int:1-53)
- ey_end: ano de final da consulta (int:2010-9999)

# Saídas / Salidas / Output

* Dados de saída / Datos de salida / Output data
* Destino / Destiny
* Formatos / Output format
* Onde e como os dados serão apresentados / Dónde y cómo los datos serán presentados / When and how data will be presented

opção de download do resultado da api referente a consulta realizada.

# Processamento / Procesamiento / Processing

* Fluxo de trabalho / Flujo de trabajo / Workflow

**Comment by xmnlab** [comment]
> Melhorar a usabilidade do acesso aos dados do infodengue para não programadores, criando uma interface com caixa de texto semelhante ao do servidor de mapas, para gerar uma tabela csv servido pela API usando datatables.

@claudia-codeco  poderias detalhar mais essa interface com caixa de texto?

**Comment by claudia-codeco** [comment]
@xmnlab 

Pensei em algo mais simples agora,  poderia ser meramente um botão de download ao lado das tabelas , nos relatorios. O que acha? Para que os gestores possam baixar as tabelas para uso.

**Comment by xmnlab** [comment]
me parece boa ideia.

então, basicamente, vamos ter os seguintes campos:

geocode: código IBGE da cidade
disease: tipo de doença a ser consultado (str:dengue|chikungunya|zika)
format: formato de saída dos dados (str:json|csv)
ew_start: semana epidemiológica de início da consulta (int:1-53)
ew_end: semana epidemiológica de final da consulta (int:1-53)
e_year: ano de referência da consulta (int:0-9999)

e um botão para baixar o arquivo, correto?

**Comment by claudia-codeco** [comment]
certo! com uma pequena modificação:

geocode: código IBGE da cidade
disease: tipo de doença a ser consultado (str:dengue|chikungunya|zika)
format: formato de saída dos dados (str:json|csv)
ew_start: semana epidemiológica de início da consulta (int:1-53)
ano_start: ano de inicio da consulta (int: 2010-9999)
ew_end: semana epidemiológica de final da consulta (int:1-53)
ano_end: ano de final da consulta (int:2010-9999)

**Comment by xmnlab** [comment]
ok! vou ter q fazer ajuste tb na api .. porque na especificação da api foi descrito somente um ano.

**Comment by xmnlab** [comment]
ano_start e ano_end .. vou trocar por ey_start e ey_end .. para manter o padrão da nomenclatura da semana.

**Comment by claudia-codeco** [comment]
OK!

**Comment by xmnlab** [comment]
@claudia-codeco 

> incluir na tabela servida, uma coluna com numero acumulado de casos no ano,

e caso for selecionado um periodo entre 2 ou mais anos?

**Comment by claudia-codeco** [comment]
nesse caso, calcula no ultimo ano.

**Comment by xmnlab** [comment]
Então seria pegar o ano final da consulta e somar todos os casos notificados, desde a semana 1 até a última semana na base de dados, sem usar a semana de inicio e final como parâmetro. 

Seria isso?

**Comment by claudia-codeco** [comment]
Sim, isso mesmo. Eles tem um critério que é alertar quando o número de
casos no ano passa de 300 por 100.000 habitantes, por isso o cálculo

Em Sex, 20 de abr de 2018 10:44, Ivan <notifications@github.com> escreveu:
