### ISSUE TITLE
Discrepância de casos reportados de chikungunya entre as páginas do estado, e município

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#193]
Município onde isso pode ser percebido:

 - Santo antônio de pádua
 - Itaocara 
 - São Fidelis
 - Itaboraí
 - Rio de Janeiro

**Comment by xmnlab** [comment]
@fccoelho

estava verificando aqui e na página de estado, o mapa que ele apresenta, ele utiliza a seguinte view:

```sql
CREATE MATERIALIZED VIEW "Municipio".historico_casos AS 

SELECT 
    dengue."data_iniSE",
    dengue."SE",
    COALESCE(dengue.casos_est, 0.0) +
      COALESCE(chik.casos_est, 0.0) +
      COALESCE(zika.casos_est, 0.0) AS casos_est,
    COALESCE(dengue.casos_est_min, 0) +
      COALESCE(chik.casos_est_min, 0) +
      COALESCE(zika.casos_est_min, 0) AS casos_est_min,
    COALESCE(dengue.casos_est_max, 0) +
      COALESCE(chik.casos_est_max, 0) +
      COALESCE(zika.casos_est_max, 0) AS casos_est_max,
    COALESCE(dengue.casos, 0) +
      COALESCE(chik.casos, 0) +
      COALESCE(zika.casos, 0) AS casos,
    dengue.municipio_geocodigo
FROM 
    "Municipio"."Historico_alerta" AS dengue
    FULL OUTER JOIN "Municipio"."Historico_alerta_chik" AS chik
        ON dengue."SE" = chik."SE"
        AND dengue.municipio_geocodigo = chik.municipio_geocodigo
    FULL OUTER JOIN "Municipio"."Historico_alerta_zika" AS zika
        ON dengue."SE" = zika."SE"
        AND dengue.municipio_geocodigo = zika.municipio_geocodigo
``` 

em outras palavras, não importa qual seja a doença selecionada, ele vai retornar a soma de todas as doenças.

**Comment by fccoelho** [comment]
Ok, então nesse e casos precisamos colocar isso escrito na legenda, pois
todas as outras visualizações são por doença...

Em seg, 7 de mai de 2018 17:41, Ivan <notifications@github.com> escreveu:

**Comment by xmnlab** [comment]
O que sugere de legenda? 

Texto atual:

- "Número de casos estimados na semana:"

Sugestões:

1. "Número de casos estimados na semana para todas as doenças:"
2. "Número de casos estimados na semana para Dengue, Chikungunya e Zika:"

**Comment by claudia-codeco** [comment]
Pode ser total de casos de arboviroses

Em Seg, 7 de mai de 2018 19:29, Ivan <notifications@github.com> escreveu:
