### ISSUE TITLE
Desligar a Zika do site

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#195]
# Objetivos / Objectivos / Purpose
Desligar os mapas de zika no site 
## Geral / General

* Objetivo da solicitação / Objectivo de la solicutud / Purpose of the request
Tirar informacoes sobre zika porque não as temos. Deixar comentado
## Específicos / Specific

* Funcionalidades [desejadas / deseadas] / Desired functionalities

# Justificativa / Justification

* Problemas que se pretende resolver / Problems that are to be solved

# Entradas / Input

* [Dados / Datos] de entrada / Input data
* Origem / Origen / Source 
* Formatos / Input format
* Significado de cada atributo / Meaning of each attribute

# Saídas / Salidas / Output

* Dados de saída / Datos de salida / Output data
* Destino / Destiny
* Formatos / Output format
* Onde e como os dados serão apresentados / Dónde y cómo los datos serán presentados / When and how data will be presented

# Processamento / Procesamiento / Processing

* Fluxo de trabalho / Flujo de trabajo / Workflow

**Comment by fccoelho** [comment]
@xmnlab this issue is no longer relevant, since now we are tracking Zika in many Municipalities.
Closing.
