### ISSUE TITLE
Base de tests

### ISSUE THREAD

**Issue by eltonn** [AlertaDengue/AlertaDengue#199]
# Objetivos / Objectivos / Purpose

## Geral / General

Onde posso encontrar uma base de tests para testar localmente o projeto?

**Comment by fccoelho** [comment]
@eltonn, temos um ambiente de testes configurado, chamado de infostaging. talvez o @xmnlab possa te dar uma luz de como configurar e usar.

**Comment by eltonn** [comment]
> @eltonn, temos um ambiente de testes configurado, chamado de infostaging. talvez o @xmnlab possa te dar uma luz de como configurar e usar.

grato, falei com ele e já estamos trabalhando nisso.

**Comment by eltonn** [comment]
Base recebida,

grato
