### ISSUE TITLE
correção das traduções em inglês e espanhol. 

### ISSUE THREAD

**Issue by eltonn** [AlertaDengue/AlertaDengue#205]
# Objetivos / Objectivos / Purpose

## Geral / General

* Objetivo da solicitação é ajustar os arquivos .PO das traduções para os idiomas inglês e espanhol.

## Específicos / Specific

ajustar tradução do arquivo: AlertaDengue/locale/en/LC_MESSAGES/django.po
ajustar tradução do arquivo: AlertaDengue/locale/es/LC_MESSAGES/django.po

Extra: 
https://github.com/AlertaDengue/AlertaDengue/pull/204/files#diff-022947d874a282beb84d6ac91c8bc9faR504

#201 #204

**Comment by esloch** [comment]
This issue was resolved
