### ISSUE TITLE
Atualizar o django nas dependencias (requirements etc)

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#209]
# Objetivos / Objectivos / Purpose

## Geral / General

Pinnar django>=2.0.11 nas listas de dependencias do projeto e corrigir os possiveis problemas relacionados a quebra de compatibilidade

## Específicos / Specific

- Pinnar django>=2.0.11 nos arquivos:
  - AlertaDengue/requirements-conda.txt
  - AlertaDengue/requirements.txt
- corrigir os possiveis problemas relacionados a quebra de compatibilidade

# Justificativa / Justification

Pode haver problemas de vulnerabilidade

**Comment by eltonn** [comment]
A versão do Django não está mais pinada nos arquivos: AlertaDengue/requirements.txt e AlertaDengue/environment.yml
