### ISSUE TITLE
Utilização da lib Ibis para facilitar requisições ao banco.

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#212]
# Objetivos / Objectivos / Purpose

## Geral / General

Trocar as expressões SQL complexas por expressões com a biblioteca ibis (https://github.com/ibis-project/ibis).

## Específicos / Specific

- Identificar as expressões complexas (por exemplo, com `if`s ou fragmentada por todo o código);
- adicionar conexão com o banco de dados usando ibis no settings.py; 
- trocar essas expressões por expressões com ibis;

# Justificativa / Justification

No código do projeto, existem algumas sentencias SQL muito customizadas e, como se pode imaginar, fica bastante difícil de entender e dar manutenção.

com o uso da biblioteca ibis fica muito mais fácil criar expressões para requisitar ao servidor de banco de dados.

**Comment by esloch** [comment]
Done!
