### ISSUE TITLE
Documentar a configuração do ambiente de desenvolvimento

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#213]
# Objetivos / Objectivos / Purpose

Criar um arquivo Markdown com um tutorial passo-a-passo da configuração do ambiente de desenvolvimento.

**Comment by xmnlab** [comment]
algumas referencias:

- https://github.com/ibis-project/ibis/blob/master/docs/source/developer.rst
- https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md

possivelmente essas novas infos deveriam estar num arquivo `CONTRIBUTING.md`

talvez inicialmente não vai ter muita informação, mas seria bom adicionar (futuramente) informações sobre os comandos `make`, informações sobre os containers, configuração local settings.ini ... alguns detalhes sobre extra sobre debug etc também sobre o canal no telegram do alertadengue

**Comment by fccoelho** [comment]
concordo em colocar como `CONTRIBUTING.md`. 
Vamos incrementando gradualmente.

**Comment by eltonn** [comment]
Closes #213
