### ISSUE TITLE
plotly.graph_objs.YAxis is deprecated

### ISSUE THREAD

**Issue by eltonn** [AlertaDengue/AlertaDengue#221]
# Objetivos / Objectivos / Purpose

## Geral / General

* Objetivo da solicitação é corrigir a função que está obsoleta.

# Justificativa / Justification

*  Em próximas versão talvez não irá funcionar.

**Comment by fccoelho** [comment]
Ok, bom você estar se familiarizando com o plotly, pois tenho o interesse de substituir alguns outros gráficos do site pelo plotly.

**Comment by fccoelho** [comment]
@eltonn vou aumentar a prioridade desta issue, pois precisamos melhorar a usabilidade do site, do ponto de vista da qualidade da informação oferecida nos gráficos. Acho que podemos a trocar outros gráficos feitos com  highcharts para plotly, o que vc acha? 
Uma outra possibilidade é usar o [Altair](https://altair-viz.github.io)

**Comment by eltonn** [comment]
@fccoelho, ok. vou analisar o Altair.

**Comment by eltonn** [comment]
Optamos por usar o plotly na versão 4.

Closes #221
