### ISSUE TITLE
Populacao usada para calcular incidencia na API

### ISSUE THREAD

**Issue by lsbastos** [AlertaDengue/AlertaDengue#237]
## Geral / General

Oi pessoal, 

Ao gerar uma base de dados via API do site, será possível incluir também uma coluna com a populacao usada? Seria bem util, pois no momento nao tem a populacao, so os casos e uma variavel chamada inc (incidência?).

Teoricamente daria para recuperar a populacao a partir do numero de casos e da incidencia, exceto quando o numero de casos é 0, ai dá ruim pois fica 0/0.

**Comment by fccoelho** [comment]
Oi @lsbastos  é possível sim, mas no momento estamos com outras prioridades por conta das entregas que temos que fazer referentes aos financiamentos que temos.
Mas vou deixar esta issue aberta, e assim que der implementamos isso.

**Comment by claudia-codeco** [comment]
A API já contem a variavel populacao, Podemos fechar a issue
