### ISSUE TITLE
Disponibilizar o dicionario das variaveis na API 

### ISSUE THREAD

**Issue by lsbastos** [AlertaDengue/AlertaDengue#238]
## Geral / General

O dicionário das variáveis do csv seriam bem uteis.

Baixei os dados da cidade do Rio, e as variaveis sao

`
> str(denRio)
Classes ‘spec_tbl_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	4950 obs. of  15 variables:
 $ id          : num  312634 312635 312636 192037 192060 ...
 $ aps         : num  1 1 1 1 1 1 1 1 1 1 ...
 $ se          : num  201836 201837 201838 201609 201632 ...
 $ data        : Date, format: "2018-09-02" "2018-09-09" "2018-09-16" "2016-02-28" ...
 $ tweets      : logi  NA NA NA NA NA NA ...
 $ casos       : num  4 4 0 1 0 4 0 0 0 3 ...
 $ casos_est   : num  4 4 0 1 0 4 0 0 0 3 ...
 $ casos_estmin: num  4 4 0 1 0 4 0 0 0 3 ...
 $ casos_estmax: num  4 4 0 1 0 4 0 0 0 3 ...
 $ tmin        : num  20.1 20.1 22 24.7 19.4 ...
 $ rt          : num  1.52 1.31 0 2.05 0 ...
 $ prt1        : num  0.714 0.649 0 0.713 0 ...
 $ inc         : num  1.762 1.762 0 0.441 0 ...
 $ nivel       : num  1 1 1 1 1 2 1 1 1 1 ...
 $ sum         : num  23551 23551 23551 23551 23551
`

Algumas ate sao auto-explicativas, mas o dicionario apontando para as referencias seria legal.

**Comment by lsbastos** [comment]
Talvez esteja tudo aqui, e eu nao procurei direito.

https://info.dengue.mat.br/services/api/doc#Consulta-em-formato-CSV

**Comment by fccoelho** [comment]
Obrigado por apontar isso acho que dá para colocar as descrição das variáveis diretamente no Notebook que você citou.

**Comment by claudia-codeco** [comment]
Inclui esse issue a outro mais amplo sobre atualização da página Dados. Coloquei prioridade tbm
