### ISSUE TITLE
Melhorar tempo de resposta para relatórios

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#249]
# Objetivos / Objectivos / Purpose
O carregamentos dos relatórios como este:
https://info.dengue.mat.br/report/CE/201931
atualmente são muito lento e costume gerar erros de Timeout

* Objetivo da solicitação / Objectivo de la solicutud / Purpose of the request
Estudar possibilidades de otimização da geração desta página, talvez usando mais AJAX

**Comment by eltonn** [comment]
WIP - analisando os scripts

**Comment by eltonn** [comment]
Olá @fccoelho, o tempo de resposta do relatório foi melhorado e está disponível no branch develop no commit https://github.com/AlertaDengue/AlertaDengue/commit/09f5bd65606c1da5b5c404e145297da514e9fde6

No PR Refactoring (#240)

Verifique se está correto pois não temos dados para geração dos gráficos.

**Comment by esloch** [comment]
Talvez o refatoramento da camada de dados já resolveria o problema de performance, incluso para trabalhar com o ajax seria bom antes um refactoring da camada de dados.

**Comment by esloch** [comment]
Continue in #312
