### ISSUE TITLE
Atualizar Página Saiba Mais

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#254]
# Objetivos / Objectivos / Purpose

Atualizar a página Saiba Mais, melhorando o conteudo em portugues e ingles

* Funcionalidades [desejadas / deseadas] / Desired functionalities

Versao em portugues e ingles
Figuras nas duas linguas
Inclusao de vários links externos

# Entradas / Input

[Pagina Saiba Mais.docx](https://github.com/AlertaDengue/AlertaDengue/files/3693355/Pagina.Saiba.Mais.docx)

**Comment by esloch** [comment]
O texto em *inglês Saiba Mais/About, é para criar uma nova página ou inserir na sequência do texto do idioma português na mesma?

**Comment by claudia-codeco** [comment]
O texto em inglês é para ser carregado automaticamente quando a linguagem do browser for inglês ou não português. Da mesma forma como outras strings no site funcionam
