### ISSUE TITLE
Ajustes finais no staging

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#267]
## Pagina Saiba mais
- [x]  colocar fundo colorido nas divs que contém títulos coloridos.
- [x] Corrigir o link das produções científicas e usar texto `Publicações` como âncora para o link.
## Equipe
- [x] Adicionar Ivan
- [x] Adicionar Claudia Brandelero Rizzi - Universidade do Oeste do Paraná
## Página do Município
- [x] Adicionar link para página do estado respectivo.
- [x] Adicionar link para página do relatório correspondente.
- [x] Desligar o zoom no mapa.
## Página do Estado
- [x] widget de seleção de município acima do mapa não está funcionando. Caso não dê para consertar agora, é melhor deixar desativado.

**Comment by esloch** [comment]
Closes PR #269
