### ISSUE TITLE
Added columns in table Historico_alerta

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#271]
Eu adicionei quatro novas colunas na tabela historico_alerta, historico_alerta_chik e historico_alerta_zika, sem alterar as já existentes. 

Testar se essa modificação causa impacto no site

Criar documentação para guiar futuras modificacoes semelhantes

**Comment by fccoelho** [comment]
@esloch fechar caso já esteja resolvido

**Comment by esloch** [comment]
Não tivemos nenhum error proveniente das colunas: umidmax, tempmin, pop, Rt nas tabelas "historico_alerta, historico_alerta_chik e historico_alerta_zika". Como poderia criar a documentação das modificações?

**Comment by fccoelho** [comment]
Acho que as documentação deveria ser de como devem ser solicitadas modificações de tabelas no futuro. Era isso que vocẽ queria dizer @claudia-codeco ?

**Comment by claudia-codeco** [comment]
está bom assim
