### ISSUE TITLE
Incorporar dados climáticos  na API

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#278]
# Objetivos / Objectivos / Purpose
Expandir a API para incorporar dados climáticos.

## Específicos / Specific

Basicamente criar um novo endpoint na API REST para retornar as variáveis climáticas dado um geocódigo.

**Comment by claudia-codeco** [comment]
@esloch I included the two main climate variables , temp_min and umid_max, in the table historico_alerta. Now we can access these variables using the API. 
So, I consider the issue solved

**Comment by esloch** [comment]
Ok, thanks!
