### ISSUE TITLE
Modificar permissões de arquivos no diretório chunked-upload

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#287]
# Objetivos / Objectivos / Purpose
- Erro permissão de acesso ao Sistema de arquivos ao fazer upload de dbf
```
root@172:/Storage/sftp2/alertadengue/uploaded/chunked_uploads/2019/12# ls -la
total 48
drwxr-xr-x 12 glauco       glauco 4096 Dez 31 11:32 .
drwxrwxrwx 14 alertadengue celery 4096 Dez  2 16:46 ..
drwxr-xr-x  2 glauco       glauco 4096 Dez  2 16:49 02
drwxr-xr-x  2 glauco       glauco 4096 Dez  3 16:25 03
drwxr-xr-x  2 glauco       glauco 4096 Dez  5 12:14 05
drwxr-xr-x  2 glauco       glauco 4096 Dez  9 11:20 09
drwxr-xr-x  2 glauco       glauco 4096 Dez 10 09:25 10
drwxr-xr-x  2 glauco       glauco 4096 Dez 12 11:32 12
drwxr-xr-x  2 glauco       glauco 4096 Dez 19 17:04 19
drwxr-xr-x  2 glauco       glauco 4096 Dez 27 15:37 27
drwxrwxrwx  2 alertadengue celery 4096 Dez 30 16:25 30
drwxr-xr-x  2 glauco       glauco 4096 Dez 31 15:31 31
```

**Comment by fccoelho** [comment]
Estranho. o glauco é um usuário da TI da FGV que precisa ter conta no servidor para fins de monitoramento, mas não faz sentido que estes diretórios estejam com estas permissões.
@esloch altere as propriedade dos diretórios para o usuário correto para resolvermos isso de uma vez.

Por outro lado, se não me falha a memória, a falha era na inserção no banco e não no upload.

**Comment by esloch** [comment]
Farei as alterações para o user/group corretos, estou trabalhando para corrigir o erro de inserção na base de dados.

**Comment by esloch** [comment]
Resolved PR #288.
