### ISSUE TITLE
Refactoring state report page

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#312]
# Objetivos / Objectivos / Purpose
## Geral / General

 Melhorar o carregamento nos relatŕorios dos estados

#### Objetivo da solicitação / Objectivo de la solicutud / Purpose of the request
- [ ] [50%] Refatorar dbdata e a views:

<li> [ ] [100% ] Separar a classe de ReportStateView em funções</li>
<li> [ ]  [100%] Refatorar read_disease_data</li>
<li> [ ]  [0% ] Refatorar a função get_regional_info()</li>
<li> [ ]  [0% ] Revisar e criar testes unitários para test_views</li>

#### Específicos / Specific
Atualmente a função get_regional_info() está fazendo mais de dois loops for dentro de outro, criando dataframes de diseases x regionais_names ocasionando gargalos de desempenho na geração dos gráficos.

>>~Devido a inconsistencia de registros que são vinculados pela SE, ocorre um erro na linha X, referente a ultima  >>init_date_week:~
>>~https://github.com/AlertaDengue/AlertaDengue/blob/develop/AlertaDengue/dados/dbdata.py#L1422~
>>

**Comment by fccoelho** [comment]
@esloch o erro ocorre no momento de fazer o set_index em `df_date` só que `df_date é [criada como uma série](https://github.com/AlertaDengue/AlertaDengue/blob/b9cdfe195e5468920ac0fc5dd7e3224cbff9a180/AlertaDengue/dados/dbdata.py#L1417) (e não um dataframe) que contém um date_range criado a partir do mínimo e máximo da coluna `init_date_week` de `df`. 

Com todo o respeito, este código está muito "macarrônico"!   :-)
Se vc quer esta date_range na data frame, seria muito mais simples indexar por 'init_date_week' e aplicar um `resample('7D')`.

Acho que para resolver isso vai ser necessário refatorar este método `read_disease_data` como um todo, que aliás está enorme (quase 200 linhas!). Tem que quebrar este código em vários métodos/funções para que sejam inclusive testáveis!

**Comment by fccoelho** [comment]
@esloch, Is this issue fully solved?

**Comment by esloch** [comment]
I'm not sure, I have to review...
Thanks!
