### ISSUE TITLE
Corrigir erro de plotagem dos gráficos de tweets em ReportState

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#313]
# Objetivos / Objectivos / Purpose

Os gráficos de tweets não estão sendo plotados na página de relatórios estaduais.

## Específicos / Specific

* Menção a arboviroses nas redes sociais

![Screenshot_20200303_085136](https://user-images.githubusercontent.com/3450741/75814498-9bcf5d00-5d70-11ea-9ecf-3ee6f1047aa9.png)

**Comment by claudia-codeco** [comment]
@esloch esse issue tbm pode ser priorizado para atender a demanda da UFMG. Entendi que é fazer um grafico com a soma dos tweets a nivel estadual

**Comment by esloch** [comment]
@claudia-codeco estou finalizando neste PR aqui #346:

![Screenshot_20201223_154715](https://user-images.githubusercontent.com/3450741/103086874-8c9df200-45c4-11eb-82ac-43315bef9dee.png)
