### ISSUE TITLE
Página Saiba Mais - formatação

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#34]
Problema 1: O texto corrido não convida à leitura
Solução:
1) Colocar um índice no inicio, para que a pessoa possa acessar diretamente o bloco. OU Fazer o bloco "abrir" quando apertar o titulo.
Problema 2: faltou colocar o email do projeto na ultima linha do texto: 
Em caso de dúvidas, entre em contato conosco:  alerta-dengue@fiocruz.br

**Comment by fccoelho** [comment]
Que texto? Que bloco?

2016-02-25 13:10 GMT-03:00 claudia-codeco <notifications@github.com>:

> Problema: O texto corrido não convida à leitura
> Solução:
> 1) Colocar um índice no inicio, para que a pessoa possa acessar
> diretamente o bloco.
> ou
> 2) Fazer o bloco "abrir" quando apertar o titulo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlertaDengue/AlertaDengue/issues/34>.
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by claudia-codeco** [comment]
O texto está já organizado em blocos, mas eles estão colados um embaixo do outro como texto corrido.
