### ISSUE TITLE
Inserir coluna na tabela regional_saude

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#341]
# Objetivos / Objectivos / Purpose

## Geral / General

* Alterar tabela regional saúde. Essa tabela indica a que regional pertence cada município. 
* Acrescentar uma coluna chamada nome_macroreg para colocar informação sobre outro nível de agregação dos municípios. 
* Preencher essa coluna com NULL como default e 
* Preencher os dados para Minas Gerais, o único que temos informação no momento, que está no anexo:

![regional2_saude](https://user-images.githubusercontent.com/3450741/85714576-f0506c80-b6c0-11ea-8acb-29153f9fa6cd.png)

**Comment by esloch** [comment]
@claudia-codeco, está finalizada a alteração na tabela, se estiver tudo ok fechamos esta issue.
Agradecido

**Comment by claudia-codeco** [comment]
sim, resolvido! obrigada
