### ISSUE TITLE
Check why we are inserting  6-digit geocodes in the Notificacao table

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#365]
This [line](https://github.com/AlertaDengue/AlertaDengue/blob/ec4885a7aab40b819d6a4a8327593853f6ae091f/AlertaDengue/dbf/sinan.py#L178) should take of it. Why is it not working?

Also, [here](https://github.com/AlertaDengue/AlertaDengue/blob/ec4885a7aab40b819d6a4a8327593853f6ae091f/AlertaDengue/dbf/sinan.py#L51) we should have an `elif len(str(geocodigo)) < 7:` instead of an `else`.

**Comment by esloch** [comment]
@fccoelho, the idea is to restrict the entry of geocodes other than 7 and treat only those with 6 digits, else throws the exception:
```
def add_dv(geocodigo):
    if len(str(geocodigo)) == 7:
        return geocodigo
    elif len (str (geocodigo)) == 6: 
        return int(str(geocodigo) + str(calculate_digit(geocodigo)))
    else:
        raise ValueError('geocode does not match!')
```
Te parece?
