### ISSUE TITLE
New template for the front page 

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#367]
# Objetivos / Objectivos / Purpose

This is the proposed template for the front page for discussion. The figure shows two possibilities for the rows: "Alabama-style" or "Alaska-style".  

![image](https://user-images.githubusercontent.com/4005254/94963296-49088000-04ce-11eb-94bc-7695e738dadd.png)

- How difficult/easy it is to implement that?
- What do we need?

**Comment by esloch** [comment]
The states overview charts should work with a crossfilter, perhaps with plotly and dash is possible, or highcharts with something like JS. That means a few hours of study ... / hard, but not impossible ...

**Comment by fccoelho** [comment]
Lets leave highcharts behind. Let's migrate everything to plotly.

**Comment by esloch** [comment]
Ok!

**Comment by esloch** [comment]
@claudia-codeco, if you can specify the tables that will be used to obtain the data?

**Comment by claudia-codeco** [comment]
ok, I will do that

**Comment by claudia-codeco** [comment]
@esloch , please see if it is clear this way:

![image](https://user-images.githubusercontent.com/4005254/95392273-d84ad480-08ce-11eb-938b-34557d885675.png)

**Comment by esloch** [comment]
@claudia-codeco, na primeira imagem de exemplos se vê diferentes gráficos para receptividade e transmissão, "alabama" tem o odometro e o "alaska" os stack-bar, estão somente para demostrar os valores?
- Como calcular os indicadores: this-week e last-week?
- Os tweets não cabem no gráfico de novos casos, pois necessitamos um outro eixo e não fica legivel.

**Comment by claudia-codeco** [comment]
@esloch , os valores da primeira figura são só ilustrativos. Os valores que vamos usar estão explicados na segunda figura (ainda falta completar a especificação das outras).

- O "this week" e "last week" precisam ser especificados. Deixe um espaço pra eles, que vou fechar isso ainda com @fccoelho 
- Tweets: vamos deixar sem eles por enquanto.

**Comment by esloch** [comment]
@claudia-codeco, o dump está aprasentando erros na tabela hist.alerta:
```
dengueadmin@172:dengue> \d "Municipio"."Historico_alerta"                                                                                 
column c.relhasoids does not exist
LINE 2: ...                 c.relhasrules, c.relhastriggers, c.relhasoi...
```
A database parece ok:
```
dengueadmin@127.0.0.1:dengue> \d "Municipio"."Historico_alerta"
+---------------------+------------------------+------------------------------------------------------------------------------+
| Column              | Type                   | Modifiers                                                                    |
|---------------------+------------------------+------------------------------------------------------------------------------|
| data_iniSE          | date                   |  not null                                                                    |
| SE                  | integer                |  not null                                                                    |
| casos_est           | real                   |                                                                              |
| casos_est_min       | integer                |                                                                              |
| casos_est_max       | integer                |                                                                              |
| casos               | integer                |                                                                              |
| municipio_geocodigo | integer                |  not null                                                                    |
| p_rt1               | real                   |                                                                              |
| p_inc100k           | real                   |                                                                              |
| Localidade_id       | integer                |                                                                              |
| nivel               | smallint               |                                                                              |
| id                  | bigint                 |  not null default nextval('"Municipio"."Historico_alerta_id_seq"'::regclass) |
| versao_modelo       | character varying(40)  |                                                                              |
| municipio_nome      | character varying(128) |                                                                              |
| tweet               | numeric(5,0)           |  default NULL::numeric                                                       |
| Rt                  | numeric(5,0)           |  default NULL::numeric                                                       |
| pop                 | numeric(7,0)           |  default NULL::numeric                                                       |
| tempmin             | numeric(4,0)           |  default NULL::numeric                                                       |
| umidmax             | numeric(4,0)           |  default NULL::numeric                                                       |
| receptivo           | smallint               |                                                                              |
| transmissao         | smallint               |                                                                              |
| nivel_inc           | smallint               |                                                                              |
+---------------------+------------------------+------------------------------------------------------------------------------+
```
Vou provar o dump de outras datas.

**Comment by claudia-codeco** [comment]
o que são essas colunas

c.relhasoids

?

**Comment by esloch** [comment]
Oi @claudia-codeco, estas colunas estavam aparecendo no restore do ultimo dump que fiz ao listar as colunas de hist.alerta, refiz o processo e funcionou corretamenta a database, não entendi o porquê destas colunas...

**Comment by claudia-codeco** [comment]
OK!

**Comment by esloch** [comment]
@claudia-codeco, estou configurando o layout no django agora, o odometro tentarei mudar para ponteiro análogico como o exemplo, os dados para indicators peguei da coluna levels de momento para ter algum valor de teste:

![Screenshot_20201112_115129](https://user-images.githubusercontent.com/3450741/98955974-48f09c80-24de-11eb-8177-d6d8df26fa6d.png)

**Comment by esloch** [comment]
Oi @claudia-codeco. 
- No stack bar de situation, é a quantidade de cidades por tipo de alerta na ultima semana?
- Atualmente os valores da coluna transmissão estão 0 ou nulls, como representar estes dados no odometro de transmission?

**Comment by claudia-codeco** [comment]
Sim, seria a quantidade de cidades. Se estiver 0, indica que não há
transmissão, nesse caso vamos calcular a % de cidades diferentes de 0. Se
estiver nulo é porque não foi calculado, nesse caso, não dá para plotar a
figura, podemos deixar sem ponteiro ou com alguma cor que indique que está
desligado.

**Comment by esloch** [comment]
As barras de stacks representam os 4 níveis de alerta para as 3 últimas semanas?
![Screenshot_20201128_105109](https://user-images.githubusercontent.com/3450741/100517178-b00d8280-3167-11eb-8c24-d43242eb5b63.png)

**Comment by esloch** [comment]
seria isso @claudia-codeco ?
![Screenshot_20201201_151339](https://user-images.githubusercontent.com/3450741/100780005-f709ab00-33e7-11eb-8832-12f907528ec6.png)

**Comment by fccoelho** [comment]
na legenda do eixo y eu colocaria: "Número de municípios em cada nível"

**Comment by claudia-codeco** [comment]
de acordo com Flavio. Ficou bom!
Mas na primeira página só teremos a barrinha da ultima semana (podemos
pensar em 3 semanas, se nao ficar muito poluido visualmente). Essa completa
pode ser acessada numa página interna.

**Comment by esloch** [comment]
Ok, vou modificar o title do eixo (y) e provar as últimas 3 semanas.
Thanks

**Comment by fccoelho** [comment]
@eltonn e @esloch , criem por favor um notebook para prototiparmos estas figuras. Precisamos correr com esta issue pois o Infodengue agora vai cobrir todo o território nacional e precisamos ter uma página principal responsiva.

**Comment by esloch** [comment]
```
def get_disease_suffix(disease: str):
    """

    :param disease:
    :return:
    """
    return (
        ''
        if disease == 'dengue'
        else '_chik'
        if disease == 'chikungunya'
        else '_zika'
        if disease == 'zika'
        else ''
    )


def get_uf_by_disease(uf, disease, weeks):
    """
   
    """
    table_name = 'Historico_alerta' + get_disease_suffix(disease)

    sql = '''
        SELECT DISTINCT alerta."SE",
            alerta."Rt", alerta."data_iniSE",
            alerta.casos_est, alerta.casos, alerta.nivel, alerta.receptivo,
            alerta.municipio_geocodigo,
            city.nome, city.uf
        FROM "Municipio"."%s" AS alerta
        INNER JOIN "Dengue_global"."Municipio" AS city ON (
                    alerta.municipio_geocodigo=city.geocodigo)        
        WHERE alerta."data_iniSE" >= NOW() - interval '%s weeks'
    '''% (
        table_name,
        weeks

    )

    with db_engine.connect() as conn:
        return pd.read_sql(sql, conn)``
![two_charts](https://user-images.githubusercontent.com/3450741/115253988-4f291b80-a103-11eb-9026-5b9cdbc975dc.png)

**Comment by fccoelho** [comment]
@esloch esta consulta é muito ineficiente! você chegou a cronometrá-la? chegou a rodar o `Explain`?

Só a primeira parte da consulta no servidor levou  dezenas de segundos
```sql
dengue> explain SELECT DISTINCT alerta."SE",alerta."Rt", alerta."data_iniSE",alerta.casos_est, alerta.casos, alerta.nivel, alerta.receptivo,alerta
        .municipio_geocodigo FROM "Municipio"."Historico_alerta" as alerta;
+-----------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                          |
|-----------------------------------------------------------------------------------------------------|
| Unique  (cost=223225.25..251162.76 rows=124167 width=27)                                            |
|   ->  Sort  (cost=223225.25..226329.42 rows=1241667 width=27)                                       |
|         Sort Key: "SE", "Rt", "data_iniSE", casos_est, casos, nivel, receptivo, municipio_geocodigo |
|         ->  Seq Scan on "Historico_alerta" alerta  (cost=0.00..38128.67 rows=1241667 width=27)      |
+-----------------------------------------------------------------------------------------------------+
```
Para que você está usando distinct se as linhas não possuem duplicação?
veja como fica o custo da consulta sem o distinct:

```sql
dengue> explain SELECT alerta."SE",alerta."Rt", alerta."data_iniSE",alerta.casos_est, alerta.casos, alerta.nivel, alerta.receptivo,alerta.municipi
        o_geocodigo FROM "Municipio"."Historico_alerta" as alerta;
+------------------------------------------------------------------------------------+
| QUERY PLAN                                                                         |
|------------------------------------------------------------------------------------|
| Seq Scan on "Historico_alerta" alerta  (cost=0.00..38128.67 rows=1241667 width=27) |
+------------------------------------------------------------------------------------+
```

Além disso, o `JOIN` também é desnecessário, pois os 2 primeiros dígitos do geocódigo são o código da UF. Logo para buscar as 3 semanas de todos os municípios do estado do RJ:

```sql
dengue> SELECT alerta."SE",alerta."Rt", alerta."data_iniSE",alerta.casos_est, alerta.casos, alerta.nivel, alerta.receptivo,alerta.municipio_geocod
        igo FROM "Municipio"."Historico_alerta" as alerta WHERE alerta."data_iniSE" >= (NOW() - interval '3 weeks') and (cast(municipio_geocodigo as
         text) like '33%');
```
A consulta acima leva meros `**0.064s**`!!!

Além disso a consulta acima não vai funcionar  da mesma forma para todos os municipios pois nem todos terão dados nas últimas 3 semanas contadas a partir de **hoje**. Por exemplo no caso do RJ, acima, há apenas uma semana de dados na tabela. logo, ao invés de `Now()` tem que ser a última semana presente na tabela.

**Comment by claudia-codeco** [comment]
@esloch , aqui estão alguns cosmeticos para  pag principal. Tá bonito.
[pagina1-site.pdf](https://github.com/AlertaDengue/AlertaDengue/files/6571664/pagina1-site.pdf)

**Comment by esloch** [comment]
@claudia-codeco e @fccoelho o link *ver mais detalhes* não ficou muito bem na barra (azul) com o nome do Estado, então coloquei no painel como uma nova tab. O mesmo pode servir para outros redirecionamentos de interesse. Que os parece?

Panel:
  
![tabs_panel_20210605](https://user-images.githubusercontent.com/3450741/120879082-4a2b0900-c597-11eb-8dd3-6e3cc4c6b993.png)
  
new tab:
![mais_detalhes](https://user-images.githubusercontent.com/3450741/120879080-49927280-c597-11eb-86a9-652973cf09ca.png)

**Comment by esloch** [comment]
Corrigido o menu para acesso via mobile:

![Screenshot_20210605_115039](https://user-images.githubusercontent.com/3450741/120896153-a5d8af00-c5f6-11eb-9086-d8fd50a6becc.png)

**Comment by claudia-codeco** [comment]
A página está otima! Só precisamos alterar o texto conforme abaixo. 
As cores e fontes podem ser mantidas como no original. Só trocar o texto.

[texto-site.pdf](https://github.com/AlertaDengue/AlertaDengue/files/6701819/texto-site.pdf)

**Comment by esloch** [comment]
Capturas com o fundo azul para os mapas: 

![new_background_maps](https://user-images.githubusercontent.com/3450741/124310143-26c98e80-db42-11eb-8db1-3cec4fa22ffb.png)

Gráficos:
 
![new_background](https://user-images.githubusercontent.com/3450741/124310148-27622500-db42-11eb-8944-f6ca03d312c7.png)
