### ISSUE TITLE
Atualizar o dicionário de dados na página Dados

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#369]
# Objetivos / Objectivos / Purpose

Substituir o texto do Dicionário de Dados que está atualmente na página Dados pelo texto contido no arquivo abaixo.
O arquivo contem o texto em portugues e ingles.

[dicionariodadosAPI.txt](https://github.com/AlertaDengue/AlertaDengue/files/5343883/dicionariodadosAPI.txt)

**Comment by eltonn** [comment]
Oi @claudia-codeco, a funcionalidade do botão download da api é baixar o arquivo no formato correspondente ou abrir em tela os dados?

**Comment by claudia-codeco** [comment]
Oi @eltonn seria melhor baixar como csv
