### ISSUE TITLE
create a URL to allow access to a csv derived from the database 

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#375]
# Objetivos / Objectivos / Purpose

Create  a process to run this consultation once a week , every Monday at night. 

```sql
SELECT dt_notific,dt_sin_pri,dt_digita, cid10_codigo FROM \"Municipio\".\"Notificacao\" 
WHERE municipio_geocodigo = 3304557 AND ano_notif > 2017
```

Create a CSV and give access to it using a URL

**Comment by fccoelho** [comment]
@esloch please create a Python script to make this query and save to csv. Then add it to `cron`. You can then expose the CSV directly via nginx

**Comment by esloch** [comment]
OK! @fccoelho keep some history of these files or overwrite them day by day?

**Comment by fccoelho** [comment]
You can overwrite them, @esloch .

**Comment by esloch** [comment]
@fccoelho and @claudia-codeco, that's OK ?
https://info.dengue.mat.br/notificacao_csv/

![cron_](https://user-images.githubusercontent.com/3450741/101509411-80c0f780-3957-11eb-998a-fcbc526ef2a1.png)
![url](https://user-images.githubusercontent.com/3450741/101509438-86b6d880-3957-11eb-9e02-447f29b4e98d.png)

**Comment by claudia-codeco** [comment]
@esloch , it's good. Just checking, the order of the columns correspond to dt_notific,dt_sin_pri,dt_digita?

**Comment by esloch** [comment]
@claudia-codeco yes, it does. The csv file is not registering the names of the columns nor the orderby clause. I'm working on an app in python/pandas to fix this, but I need to build a container to run an environment and the crontab.

would be like this:

        '''
        SELECT dt_notific,dt_sin_pri,dt_digita, cid10_codigo FROM "Municipio"."Notificacao" 
        WHERE municipio_geocodigo = 3304557 AND ano_notif > 2017 ORDER BY dt_notific DESC;
        '''
```
  | dt_notific | dt_sin_pri | dt_digita | cid10_codigo
0 | 2020-11-23 | 2020-11-12 | 2020-11-23 | A90
1 | 2020-11-18 | 2020-11-06 | 2020-11-19 | A92.0
2 | 2020-11-17 | 2020-11-14 | 2020-11-18 | A92.0
```

**Comment by claudia-codeco** [comment]
@esloch OK, no problem about the header. So, we still don't have it being updated weekly, right?

**Comment by esloch** [comment]
yes, every Monday at 10 pm.

**Comment by esloch** [comment]
@claudia-codeco parece estar atendendo os requisitos. Fecharei esta issue, caso precise alguma alteração reabrimos, ok?

**Comment by claudia-codeco** [comment]
de acordo
