### ISSUE TITLE
Direcionar a caixa de busca da pagina principal para as paginas de relatorio dos mucicipios

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#382]
# Objetivo

Dar mais visibilidade ao relatorio online e simplificar a navegaçao no site:

# Tarefa

Direcionar a busca na caixa de busca da pagina inicial diretamente para o relatorio. Por exemplo, 
Foz do Iguaçu aponta para -> 
https://info.dengue.mat.br/report/PR/4108304/202050

**Comment by claudia-codeco** [comment]
podemos fechar esse issue

**Comment by esloch** [comment]
Done!
