### ISSUE TITLE
Automate e-mail to request  weekly data

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#387]
A cada semana precisamos solicitar atualizações de dados das secretarias de saúde.
Com a expansão do infodengue, precisamos automatizar estas mensagens de solicitação de dados.

### Implementation suggestion
Create a database table for registering contact emails per partner.

nome| nivel|contato|ativo
-------|-------|----------|--------
espirito Santo| estadual | fulano@gmail.com| N
Porto Alegre| municipal| beltrana@gmail.com| S

Toda semana enviar um email para cada contato. A @sarasouzabh pode preparam o texto desta mensagem padrão.

**Comment by eltonn** [comment]
Olá @fccoelho, vai ter uma aplicação responsável por gerir os dados e enviar os e-mail?
Também é possível enviar direto pelo postgresql mas não sei se é uma boa ideia.
https://github.com/captbrando/pgMail

**Comment by fccoelho** [comment]
@eltonn, podemos usar a interface admin do Django para alimentar esta tabela, e um simples script python para enviar os email acionado por CRON.

**Comment by esloch** [comment]
@fccoelho criar em models na base infodengue? Que sugeres?

**Comment by fccoelho** [comment]
sim, acho que deve ficar no mesmo app que gerencia usuários e outros detalhes administrativos do site

**Comment by esloch** [comment]
@sarasouzabh informou que este envio seria de forma seletiva, pois nem todos deixam de enviar os informes dos dados.
Talvez uma flag para selecionar para quais contatos desejamos enviar a solicitação, ¿qué opinas @fccoelho ?

![view_partners](https://user-images.githubusercontent.com/3450741/112149035-51a85c00-8bbd-11eb-94cd-8af451e76528.png)

Vou criar um script para teste e verificar como linkar a mensagem:
```
Olá, bom dia, tudo bem? 
 
Vocês já possuem  os dados de dengue, chikungunya e Zika  da SE10?
Se sim, poderiam nos enviar? 
Caso já tenha enviado , gentileza desconsiderar esse e-mail. 
 
Obrigada ,
Atenciosamente;
``` 
![edit_partners](https://user-images.githubusercontent.com/3450741/112149033-50772f00-8bbd-11eb-8c58-b044b8eb91b2.png)
