### ISSUE TITLE
Allows control of which states are active in the django-admin

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#389]
# Objetivos / Objectivos / Purpose

## Geral / General

* Inserir funcionalidades na “interface” django-admin para habilitar e desabilitar os estados participantes no Infodengue.

### Problemas que se pretende resolver / Problems that are to be solved
* Corrigir o erro na visualização dos charts ao inserir os dados dos novos estados na tabela de histórico_alerta.

## Específicos / Specific

Traceback:
```
web_1            | KeyError: 'Santa Catarina'
web_1            | Not Found: /favicon.ico
web_1            | Not Found: /favicon.ico
web_1            | Internal Server Error: /
web_1            | Traceback (most recent call last):
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1            |     response = get_response(request)
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1            |     response = self.process_exception_by_middleware(e, request)
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
web_1            |     return self.dispatch(request, *args, **kwargs)
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
web_1            |     return handler(request, *args, **kwargs)
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/views/generic/base.py", line 158, in get
web_1            |     context = self.get_context_data(**kwargs)
web_1            |   File "/srv/deploy/AlertaDengue/dados/views.py", line 474, in get_context_data
web_1            |     'chart_dengue': HomeCharts.create_dengue_chart({}),
web_1            |   File "/srv/deploy/AlertaDengue/dados/charts/home.py", line 173, in create_dengue_chart
web_1            |     return cls._create_chart(case_series, 'dengue')
web_1            |   File "/srv/deploy/AlertaDengue/dados/charts/home.py", line 110, in _create_chart
web_1            |     marker={'color': cls.colors[k]},
web_1            | KeyError: 'Santa Catarina'
```

**Comment by xmnlab** [comment]
for this issue, it would be good to add also a test for that.

so, for example, the test should check if all the states are synchronized with cls.colors

**Comment by esloch** [comment]
@fccoelho, penso em chamar este modulo a parte, temos mais algumas funcionalidades que iremos usar posteriormente; 

![common](https://user-images.githubusercontent.com/3450741/111352365-da297880-8662-11eb-8488-8aabb8b474d5.png)

**Comment by esloch** [comment]
@fccoelho podemos usar está tabela estado para isso?
```
dengueadmin@172:dengue> \d "Dengue_global".estado
+-----------+------------------------+-------------+
| Column    | Type                   | Modifiers   |
|-----------+------------------------+-------------|
| nome      | character varying(128) |  not null   |
| geojson   | text                   |  not null   |
| regiao    | character varying(32)  |  not null   |
| uf        | character varying(2)   |  not null   |
| geocodigo | integer                |  not null   |
+-----------+------------------------+-------------+
```
aqui entraria os campos de; 
- map_center_x
- map_center_y
- zoom_map
- status(*'enable'*, *'disable'*)

**Comment by fccoelho** [comment]
Sim, acho uma boa idéia.

**Comment by fccoelho** [comment]
Será que o @eltonn podia dar uma força na conclusão desta issue, @esloch ?

**Comment by eltonn** [comment]
@esloch, fico a disposição.

**Comment by esloch** [comment]
@eltonn, eu havia colocado em funcionamento a app **common** usando o models para gerar uma nova tabela chamada ```common_federatedstates ```. A query em dbdata filtrava apenas os estados que foram ativados pelo django-admin. Neste caso não fica viável usar o models do django, pois usamos a base de dados *infodengue* para isso.
A ideia agora é usar a table ```Dengue_global".estado ``` e adicionar apenas os novos campos mencionados acima *(se necessário)*.É preciso refazer toda a app com novos testes, terias de ver a melhor forma de integrar o django-admin em uma tabela que não seja gerada pelo migrate de models.

**Comment by eltonn** [comment]
@esloch, entendi.

**Comment by esloch** [comment]
- Resolved in #441

> Participating states are now selected by the *filter_active_states* method in dbdata, which filters from the STATE_NAMES dictionary
