### ISSUE TITLE
Fixes sync-geofiles

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#394]
# Objetivos / Objectivos / Purpose

## Geral / General

* Objetivo da solicitação / Objectivo de la solicutud / Purpose of the request

## Específicos / Specific

```
staging_web_1            | Successfully geojson 4212601 synchronized!
staging_web_1            | Successfully GeoJSON/simplified 4212601 synchronized!
staging_web_1            | Traceback (most recent call last):
staging_web_1            |   File "manage.py", line 13, in <module>
staging_web_1            |     execute_from_command_line(sys.argv)
staging_web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
staging_web_1            |     utility.execute()
staging_web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
staging_web_1            |     self.fetch_command(subcommand).run_from_argv(self.argv)
staging_web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
staging_web_1            |     self.execute(*args, **cmd_options)
staging_web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
staging_web_1            |     output = self.handle(*args, **options)
staging_web_1            |   File "/srv/deploy/AlertaDengue/gis/management/commands/sync_geofiles.py", line 193, in handle
staging_web_1            |     self.create_geojson(f_geojson_path, geocode)
staging_web_1            |   File "/srv/deploy/AlertaDengue/gis/management/commands/sync_geofiles.py", line 29, in create_geojson
staging_web_1            |     geojson_city = geojson.dumps(maps.get_city_geojson(int(geocode)))
staging_web_1            |   File "/srv/deploy/AlertaDengue/dados/maps.py", line 25, in get_city_geojson
staging_web_1            |     feat['type'] = 'Feature'
staging_web_1            | TypeError: 'str' object does not support item assignment
```

**Comment by esloch** [comment]
@fccoelho os dados geojson estão faltando para dois municípios de SC.
``` 

dengueadmin@172:dengue> SELECT * FROM  "Dengue_global"."Municipio" WHERE uf='Santa Catarina' and geojson='""';
+-------------+------------------+-----------+-------------+----------------+
| geocodigo   | nome             | geojson   | populacao   | uf             |
|-------------+------------------+-----------+-------------+----------------|
| 4212650     | Pescaria Brava   | ""        | 9908        | Santa Catarina |
| 4220000     | Balneário Rincão | ""        | 12212       | Santa Catarina |
+-------------+------------------+-----------+-------------+----------------+
```

**Comment by fccoelho** [comment]
Será que o Geobr consegue obter o geojson destes municípios?
Também podemos abrir o mapa do brasila a nível de município do IBGE com o geopandas, e exportar apenas estes municípios como geoJSON.

**Comment by esloch** [comment]
> Será que o Geobr consegue obter o geojson destes municípios?
> Também podemos abrir o mapa do brasila a nível de município do IBGE com o geopandas, e exportar apenas estes municípios como geoJSON.

Irei verificar estas possibilidades.

**Comment by esloch** [comment]
Os municípios listados a baixo não se encontram nos shapefiles capturados pelo br-atlas:
```
1504752 is not in this geojson: pa.
4220000 is not in this geojson: sc.
4212650 is not in this geojson: sc.
4314548 is not in this geojson: rs.
5006275 is not in this geojson: ms.
```
Tendo em conta que o br-atlas de [*carolinabigonha* ](https://github.com/carolinabigonha/br-atlas/blob/master/Makefile#L49) baixa as malhas referentes o ano 2010:
*ftp://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_municipais/municipio_2010/*

Fiz o download para conferir os municípios referente a 2019 :
*ftp://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_municipais/municipio_2019/UFs/*
e estes sim, estão contidos nos shapefiles, porém teríamos que fazer uma atualização do código. Até porque a captura atual  através de API não tem a mesma estrutura dos shapefiles baixados.

**Comment by fccoelho** [comment]
Então, os municípios que estavam faltando correspondem a municípios que não existiam em 2010. Talvez não surta resultados a curto prazo, mas podemos abrir um issue no repositório do BR-Atlas para que atualizem suas fontes.

Parece-me que o GEOBR também está baixando 2010 pelos testes que fiz, logo, seria melhor fazer a correção pontual da nossa tabela de municípios com mapas baixados do Geoftp diretamente, pois não precisaremos atualizar isto tão cedo.

**Comment by fccoelho** [comment]
Na verdade o GEOBR precisa que se especifique o ano, caso contrário baixa de 2010
