### ISSUE TITLE
Atualizar Pagina Equipe

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#396]
# Objetivos / Objectivos / Purpose

Adicionar uma subseção "Assessoria de Imprensa" e colocar o nome e contato da Marcelle.

algo assim:

## Comunicação
- [Marcelle Chagas](mailto:)

**Comment by claudia-codeco** [comment]
I suggest to update the whole page:

1. Remove "Chamada de Bolsa de Pesquisa"

2. Update and reorganize the names:

Coordenação Geral:

    Flávio Codeço Coelho, Escola de Matemática Aplicada/FGV
    Oswaldo Gonçalves Cruz, PROCC/Fiocruz
    Cláudia Torres Codeço, PROCC/Fiocruz 

Epidemiologia:

    Thais Souza Riback 
    Sara de Souza Oliveira
    Raquel Martins Lana
    Marcelo F C Gomes
    Daniel A M Villela
    Leonardo Souza Bastos

Desenvolvimento:  
    Ivan Ogasawara 
    Elton Nogueira Santana
    Sandro Loch
    Vinicius Godinho  

Comunicação:
    Marcelle Chagas

Colaboradores:

    Karina Talita O S Jorge - Observatório da Dengue/UFMG
    Mauro Martins Teixeira - Observatório da Dengue/UFMG
    Magda C V C Ribeiro - Instituto de Biociências/UFPR 
 
Colaboradores internacionais: manter os mesmos

 Alunos (manter os mesmos)

Parceria:

    Observatório da Dengue
    Secretaria Estadual de Saúde do Rio de Janeiro
    Secretaria Estadual de Saúde do Estado do Espírito Santo
    Secretaria Estadual de Saúde do Estado do Paraná
    Secretaria Estadual de Saúde do Estado do Ceará
    Secretaria Estadual de Saúde do Estado de Minas Gerais
    Secretaria Estadual de Saúde do Estado do Maranhão
    Secretaria Estadual de Saúde do Estado de Santa Catarina
    Secretaria Municipal de Saúde/Rio de Janeiro/RJ
    Secretaria Municipal de Saúde de São José do Rio Preto/SP   
    Secretaria Municipal de Saúde de Bauru/SP   
    Secretaria Municipal de Saúde de Sorocaba/SP
    Secretaria Municipal de Saúde do Rio Grande do Sul/RS

Apoio:

    DECIT/MS (2014 – 2016)
    Fiocruz Edital Inova 2019 (2019-2021) 
    FNS/MS (2020-2021)

Oportunidade:

    No momento não temos posições abertas, mas se você tem formação em ciência de dados, tem conhecimento de R ou Python, e tem interesse em colaborar com o Infodengue, mande seu currículo.

**Comment by esloch** [comment]
- Closes #409.
