### ISSUE TITLE
Flexibilização da API 

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#399]
Para facilitar as consultas do Aplicativo movel, seria interessante que as chamadas da API, atualmente seguindo o seguinte padrão:

https://info.dengue.mat.br/api/alertcity/?geocode=3304557&disease=dengue&format=json&ew_start=05&ey_start=2021&ew_end=09&ey_end=2021

Possam ter apenas os parâmetros `geocode` , `disease` e `format` como obrigatórios. Os demais teriam como default o ano corrente e a última semana epidemiológica disponíveis.

**Comment by fccoelho** [comment]
Outro default útil é: no caso de `disease` não ser especificado, retornar a ultima semana de cada doença.

**Comment by esloch** [comment]
> Outro default útil é: no caso de disease não ser especificado, retornar a ultima semana de cada doença.

@fccoelho vou criar uma issue para tratar este caso por separado.

**Comment by esloch** [comment]
@fccoelho. Fixei em two weeks ago a data de inicio para obter o resultado da última semana digitada.
Penso que talvez este parametro possa ser definido no arquivo *.env* caso necessites algum período maior para o aplicativo.
```
dt_end = datetime.datetime.now()
dt_start = dt_end - datetime.timedelta(weeks=2)   
```


![URI_JSON_API_](https://user-images.githubusercontent.com/3450741/110905045-9e03ba00-82e8-11eb-9396-526c73c83350.png)

**Comment by fccoelho** [comment]
Acho ótima a possibilidade de configurar isso no `.env`, mas seria ainda mais fácil para a administração do site, se isto estivesse no `admin site`, lembra que temos uma issue aberta para criar o `admin site`?

**Comment by fccoelho** [comment]
o .env, pode definir o default, mas deveria ser configurável no admin site.

**Comment by esloch** [comment]
> Outro default útil é: no caso de `disease` não ser especificado, retornar a ultima semana de cada doença.

@fccoelho, tentei esse default para o PR #488, mas se torna muito custoso usar mais de um **loop for** dentro de outro **loop for**.
Eu teria de estudar uma melhor forma. Se consideras necessário reabrimos essa issue.
