### ISSUE TITLE
Criar tabelas Alerta por regional

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#426]
Como parte do desenvolvimento do alerta a nível nacional, precisaremos criar mais 3 tabelas:

1.  **alerta_regional_dengue**
2.  **alerta_regional_chik**
3.  **alerta_regional_zika**

Todas com a estrutura abaixo:

| Column              | Type                   | Modifiers                                                
|---------------------|------------------------|----------------------------------------------------------
| id                  | bigint                 |  serial
| data_iniSE          | date                   |  not null                                                
| SE                  | integer                |  not null                                                
| casos_est           | real                   |                                                          
| casos_est_min       | real                |                                                          
| casos_est_max       | real                |                                                          
| casos               | integer                |                                                          
| regional_codigo | integer                |  not null                                                
| p_rt1               | real                   |                                                          
| p_inc100k           | real                   |                                                          
| uf                     | varchar(2)                                        
| nivel               | smallint               |                                                                                                                 
| regional_nome      | character varying(128) |                                                          
| tweet               | numeric(5,0)           |  default NULL::numeric                                   
| Rt                  | numeric(5,0)           |  default NULL::numeric                                   
| pop                 | numeric(7,0)           |  default NULL::numeric                                   
| tempmin             | numeric(4,0)           |  default NULL::numeric             
| tempmed             | numeric(4,0)           |  default NULL::numeric     
| tempmax             | numeric(4,0)           |  default NULL::numeric       
| umidmin             | numeric(4,0)           |  default NULL::numeric
| umidmed             | numeric(4,0)           |  default NULL::numeric          
| umidmax             | numeric(4,0)           |  default NULL::numeric                                   
| receptivo           | smallint               |                                                          
| transmissao         | smallint               |        
| nivel_inc              | smallint            |

**Comment by eltonn** [comment]
WIP:
@fccoelho , o id será uma primary key?
os atributos "regional_codigo" e "regional_nome" possuem na tabela de regional.
Acha interessante ter um relacionamento com a tabela regional, inserindo uma foreign key regional_id nestas tabelas?

**Comment by eltonn** [comment]
Script: **alerta_regional_dengue**

		CREATE TABLE IF NOT EXISTS "Dengue_global"."alerta_regional_dengue"
		(
			id	bigserial,
			data_iniSE	date	not null,
			SE	integer	not null,
			casos_est	real,
			casos_est_min	real,	
			casos_est_max	real,	
			casos	integer,	
			regional_codigo	integer	not null,
			p_rt1	real,	
			p_inc100k	real,	
			uf	varchar(2),	
			nivel	smallint,	
			regional_nome	character varying(128),	
			tweet	numeric(5,0),
			Rt	numeric(5,0),
			pop	numeric(7,0),
			tempmin	numeric(4,0),
			tempmed	numeric(4,0),
			tempmax	numeric(4,0),	
			umidmin	numeric(4,0),	
			umidmed	numeric(4,0),	
			umidmax	numeric(4,0),
			receptivo	smallint,
			transmissao	smallint,	
			nivel_inc	smallint
		);

**Comment by fccoelho** [comment]
SIm o Id será primary key, e sim pode substituir a `regional_codigo` e `regional_nome` pelo relacionamento com  a tabela regional

**Comment by eltonn** [comment]
@fccoelho  e @claudia-codeco, a issue está concluída.
Executei o script de criação das tabelas no servidor da fgv.
