### ISSUE TITLE
Redirecionar as consultas na tabela regional_saude para a tabela parameters(importante para o info nacional)

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#435]
# Objetivos / Objectivos / Purpose

Atualmente, o site consulta a tabela regional_saude para fazer graficos que precisam das variaveis :
limiar_preseason, limiar_posseason, limiar_epidemico, varcli, tcrit, ucrit 

O objetivo é direcionar essa consulta para a tabela parameters, que é mais flexivel para acomodar parametros gráficos para diferentes doencas.  

* Problemas que se pretende resolver / Problems that are to be solved

Os graficos atuais do boletim dos municipios só permite uma variavel climatica, mas há municipios que utilizam duas variaveis climaticas. Com a tabela parameters , poderemos usar parametros (limiares) diferentes para cada doença.

# Entradas / Input

A tabela abaixo mostra as semelhanças e diferenças entre a tabela antiga (regionais_saude) e a nova (parameters). 
A tabela nova tem as mesmas variaveis anteriores, em sua maioria. Importantes diferenças são:
- a tabela parameters não tem informação de regional e macroregiao, pois tem tabelas especificas para isso
- a tabela parameters codifica de forma diferente as variaveis climaticas. Agora temos dois pares de (nome variavel, valor variavel) chamados varcli, clicrit;  e varcli2, clicrit2. 
- a tabela parameters tem cid10, que vai permitir ter valores diferentes de parametros para cada doença    
	

Tabela  			 			regional_saude | Tabela  			 			parameters | Descrição 			das diferenças
-- | -- | --
municipio_geocodigo | municipio_geocodigo | &nbsp;
id_regional | &nbsp; | Se precisar 			id_regional, consultar tabela regional
codigo_estacao_wu | codigo_estacao_wu | &nbsp;
nome_regional | &nbsp; | Se precisar 			nome_regional, consultar tabela regional
limiar_preseason | limiar_preseason | &nbsp;
limiar_posseason | limiar_posseason | &nbsp;
limiar_epidemico | limiar_epidemico | &nbsp;
estacao_wu_sec | estacao_wu_sec | &nbsp;
varcli | varcli | &nbsp;
tcrit | &nbsp; | Na 			tabela parameters, no lugar da tripla(varcli,tcrit, ucrit) , temos 			a dupla (varcli, clicrit) onde varcli é o nome da variavel 			climatica principal e clicrit é o valor critico dessa variavel.
ucrit | &nbsp;
nome_macroreg | &nbsp; | Se precisar 			nome_macroreg, consultar tabela macroregional
&nbsp; | clicrit | &nbsp;
&nbsp; | varcli2 | Na 			tabela parameters, temos a especificacao de uma segunda dupla 			(varcli2, clicrit2) onde varcli2 é o nome da variavel climatica 			secundária e clicrit é o valor critico dessa variavel.  Nem 			todos os municipios tem
&nbsp; | clicrit2
&nbsp; | codmodelo | Nome do 			modelo climatico usado.
&nbsp; | cid10 | Por enquanto 			estamos usando os mesmos parametros para todas as doenças. Mas, 			eventualmente teremos: “A90”,”A92.0”,”A92.8”  			 			para dengue, chik e zika, respectivamente

# Saídas / Salidas / Output

- Espera-se tornar a tabela regional_saude obsoleta, uma vez que todas as informacoes já estão disponiveis em outras tabelas.
Para isso, o site precisa consultar a tabela parameters, ao inves da tabela regional_saude.

- Nos municipios com duas variaveis climaticas, varcli e varcli2 - ter a opção de escolher a variavel no gráfico do relatorio. Ou plotar as duas no mesmo gráfico.

**Comment by claudia-codeco** [comment]
@esloch , desculpe, nao sei se preciso fazer algo aqui

**Comment by esloch** [comment]
@claudia-codeco e @fccoelho, alguma alteração nas visualizações dos dados quanto as novas variáveis?
### Relatório da Situação das Arboviroses (Municípal)
![data_table_variables](https://user-images.githubusercontent.com/3450741/141107228-b92c869f-d9e4-46af-9906-6774b0154673.png)
*"Dengue_global".parameters*
```
    ['municipio_geocodigo',
     'limiar_preseason',
     'limiar_posseason',
     'limiar_epidemico',
     'varcli',
     'clicrit',
     'cid10',
     'codmodelo',
     'varcli2',
     'clicrit2',
     'codigo_estacao_wu',
     'estacao_wu_sec']
``` 
![chart_climate_condition](https://user-images.githubusercontent.com/3450741/141107230-42c0b3ac-8ff0-4b5d-b3ed-63a250aa9b0f.png)
![treshhold_epidemic_chart](https://user-images.githubusercontent.com/3450741/141107232-3b6701a1-f6bb-41d7-b639-5db223b82f7d.png)

**Comment by claudia-codeco** [comment]
Temos que fazer modificações no segundo e terceiro grafico. Vou encaminhar
proposta para discussão na reuniao amanhã.

**Comment by claudia-codeco** [comment]
Precisamos corrigir esse gráfico abaixo, porque ele não está muito claro.  Você poderia postar o código aqui para eu dar uma olhada?



![image](https://user-images.githubusercontent.com/4005254/141312321-6f4f73ad-9759-4530-81cf-2b7c014f17e8.png)

**Comment by esloch** [comment]
> Precisamos corrigir esse gráfico abaixo, porque ele não está muito claro. Você poderia postar o código aqui para eu dar uma olhada?

**Aqui o código da estrutura do gráfico:**
https://github.com/AlertaDengue/AlertaDengue/blob/main/AlertaDengue/dados/charts/cities.py#L20


**Os parâmetros junto com os dataframes para cada disease são fornecidos pela views**
https://github.com/AlertaDengue/AlertaDengue/blob/main/AlertaDengue/dados/views.py#L1133

    df_dengue = ReportCity.read_disease_data(
        geocode=geocode,
        disease_code=CID10['dengue'],
        station_id=station_id,
        year_week=year_week,
        var_climate=var_climate,
        has_tweets=True,
    )

    df_chik = ReportCity.read_disease_data(
        geocode=geocode,
        disease_code=CID10['chikungunya'],
        station_id=station_id,
        year_week=year_week,
        var_climate=var_climate,
        has_tweets=False,
    )

    df_zika = ReportCity.read_disease_data(
        geocode=geocode,
        disease_code=CID10['zika'],
        station_id=station_id,
        year_week=year_week,
        var_climate=var_climate,
        has_tweets=False,
    )

**O método read_disease_data é criado em dbdata:**
https://github.com/AlertaDengue/AlertaDengue/blob/main/AlertaDengue/dados/dbdata.py#L1152

@claudia-codeco, se quiseres tento passar tudo para um notebook...

**Comment by claudia-codeco** [comment]
@esloch  as modificacoes são as seguintes:

**Grafico de clima:**

O grafico original é:

![image](https://user-images.githubusercontent.com/4005254/141776516-6a09cd2a-b54d-459f-a967-e9c6f34f9ced.png)

Nova versão:
Teremos municipios com dois graficos e municipios com um grafico apenas porque para algumas cidades temos duas variaveis climaticas para mostrar. Pensei de fazer algo como nesse exemplo, com o eixo x compartilhado:

![image](https://user-images.githubusercontent.com/4005254/141779014-e5ecb082-8623-46cf-8f3f-5a980f9acf94.png)

  
A primeira sub-figura é um grafico de linha:
 varcli = (temp_min, umid_min, umid_max) é o nome da variavel climatica 
clicrit = numerico é a linha horizontal (limiar favoravel) 

A segunda figura só será se varcli2 for diferente de NULL
varcli2 = (temp_min, umid_min, umid_max) é o nome da variavel climatica 
clicrit2 = numerico é a linha horizontal (limiar favoravel) 

**Estilo**

em termos de estilo, tem como colorir o grafico mostrando a area acima e abaixo da linha de referencia, como na figura abaixo?

![image](https://user-images.githubusercontent.com/4005254/141780055-a7ce2445-9e13-4bba-89d8-23a2c3580dd9.png)

**Comment by esloch** [comment]
Certo! Vou começar com um notebook.
Agradecido.

**Comment by esloch** [comment]
@claudia-codeco 
O que os parece se fizermos uma espécie de normalização de dados com essa tabela "Dengue_global"."parameters"; Em vez de termos os campos; **[varcli, varlci2, tcri, tcri2]**, 
criar o nome dos campos como **[temp_min, umid_min, umid_max,...]**, para  assim ir eliminando a redundância dos dados? Teríamos um impacto muito grande nas dependências/scripts?
 
``` 
dengueadmin@localhost:dengue> SELECT varcli, count(*)   FROM "Dengue_global"."parameters" GROUP BY varcli;
+----------+---------+
| varcli   | count   |
|----------+---------|
| temp_min | 4876    |
| umid_min | 18      |
| umid_max | 670     |
+----------+---------+
SELECT 3
Time: 0.037s
dengueadmin@localhost:dengue> SELECT varcli2, count(*)   FROM "Dengue_global"."parameters" GROUP BY varcli2;
+-----------+---------+
| varcli2   | count   |
|-----------+---------|
| <null>    | 3257    |
| NA        | 10      |
| umid_min  | 523     |
| umid_max  | 1774    |
+-----------+---------+
```

**Comment by claudia-codeco** [comment]
Aqui nao é exatamente uma redundancia. Para cada municipio, nós temos um
modelo de decisao que usa 1 ou 2 variáveis climaticas, que sao varcli1 e
varcli2. Como as variaveis podem ser diferentes, entao elas estao
especificadas na tabela de parametros.
O gerador de alerta vai consultar a(s) variaveis indicadas na hora de rodar
o pipeline.

A alternativa seria fazer uma tabela muito maior, com todas as variaveis
climaticas, sendo que a maior parte das colunas seriam nulas, pois só
usamos duas vars em cada municipio. Ficou clara minha explicacao?

**Comment by xmnlab** [comment]
creio que o que o @esloch quis dizer referente a redundancia de dados é os textos "umid_min", "umid_max" e "temp_min" se repetem na base de dados com bastante frequencia e isso pode sugerir que a base não está otimizada.

se a coluna é do tipo categoria, pode ser trocada por um tipo de dados tipo ENUM (se a base de dados suporta), ou ter algo como uma tabela de variaveis climáticas e ter como foreign keys apontando pra essa tabela.

outra sugestão seria ter uma tabela "auxiliar" que estaría relacionado os municipios com as variaveis climáticas.

cada nível de normalização da base de dados tem como propósito deixar a base de dados mais organizada e menos repetição de dados, mas isso tb pode aumentar a complexidade das consultas ou manutenção ... mas acredito que manter essa variavel com texto realmente nao é boa abordagem.

**Comment by claudia-codeco** [comment]
parece-me correto.

**Comment by fccoelho** [comment]
> creio que o que o @esloch quis dizer referente a redundancia de dados é os textos "umid_min", "umid_max" e "temp_min" se repetem na base de dados com bastante frequencia e isso pode sugerir que a base não está otimizada.
> 
> se a coluna é do tipo categoria, pode ser trocada por um tipo de dados tipo ENUM (se a base de dados suporta), ou ter algo como uma tabela de variaveis climáticas e ter como foreign keys apontando pra essa tabela.
> 
> outra sugestão seria ter uma tabela "auxiliar" que estaría relacionado os municipios com as variaveis climáticas.
> 
> cada nível de normalização da base de dados tem como propósito deixar a base de dados mais organizada e menos repetição de dados, mas isso tb pode aumentar a complexidade das consultas ou manutenção ... mas acredito que manter essa variavel com texto realmente nao é boa abordagem.

O postgreSQL tem o tipo enum: https://www.postgresql.org/docs/14/datatype-enum.html

**Comment by esloch** [comment]
@fccoelho, para a construção do gráfico climático são usados os campos **[temp_min, umid_max e umid_min]**
Se fizer uma consulta para o município de Alagoinhas código: 2900702, apresenta o erro de index não encontrado:
*report/RJ/2900702/202210*
```
Exception Type: | KeyError
"['umid.min'] not in index"
``` 
O campo **[umidmin]** não se encontra na tabela *"Municipio"."Historico_alerta"*
``` 
dengue> \d "Municipio"."Historico_alerta"
+---------------------+------------------------+------------------------------------------------------------------------------+
| Column              | Type                   | Modifiers                                                                    |
|---------------------+------------------------+------------------------------------------------------------------------------|
| data_iniSE          | date                   |  not null                                                                    |
| SE                  | integer                |  not null                                                                    |
| casos_est           | real                   |                                                                              |
| casos_est_min       | integer                |                                                                              |
| casos_est_max       | integer                |                                                                              |
| casos               | integer                |                                                                              |
| municipio_geocodigo | integer                |  not null                                                                    |
| p_rt1               | real                   |                                                                              |
| p_inc100k           | real                   |                                                                              |
| Localidade_id       | integer                |                                                                              |
| nivel               | smallint               |                                                                              |
| id                  | bigint                 |  not null default nextval('"Municipio"."Historico_alerta_id_seq"'::regclass) |
| versao_modelo       | character varying(40)  |                                                                              |
| municipio_nome      | character varying(128) |                                                                              |
| tweet               | numeric(5,0)           |  default NULL::numeric                                                       |
| Rt                  | numeric(5,0)           |  default NULL::numeric                                                       |
| pop                 | numeric(7,0)           |  default NULL::numeric                                                       |
| tempmin             | numeric(4,0)           |  default NULL::numeric                                                       |
| umidmax             | numeric(4,0)           |  default NULL::numeric                                                       |
| receptivo           | smallint               |                                                                              |
| transmissao         | smallint               |                                                                              |
| nivel_inc           | smallint               |                                                                              |
+---------------------+------------------------+------------------------------------------------------------------------------+
``` 
O que podemos fazer aqui?

**Comment by fccoelho** [comment]
@claudia-codeco did you eliminate umidmin from the historico alerta table or did it never exist there?

**Comment by claudia-codeco** [comment]
It never existed; my suggestion is to add these variables to historico_alerta:

umidmin
umidmed
tempmed
tempmax

and I will include them in the AlertTools object.

**Comment by esloch** [comment]
@claudia-codeco, is it possible to send me the output.sql script of the nowcasting? I can locally test these changes in the table before doing it in production?

**Comment by viniciusbgodinho** [comment]
@esloch rodamos o nowcasting juntos no começo da semana para o teste.

**Comment by esloch** [comment]
@claudia-codeco, temos como identificar o porque está chegando 'NA's em **varcli2** na tabela **"Dengue_global".parameters **?
``` 
dengue=# SELECT * FROM "Dengue_global".parameters WHERE municipio_geocodigo=2900702 LIMIT 10;                                                                                               
 row.names | municipio_geocodigo | limiar_preseason | limiar_posseason | limiar_epidemico |  varcli  | clicrit | cid10 | codmodelo | varcli2 | clicrit2 | codigo_estacao_wu | estacao_wu_sec 
-----------+---------------------+------------------+------------------+------------------+----------+---------+-------+-----------+---------+----------+-------------------+----------------
           |             2900702 | 3.28241217906215 | 3.28241217906215 | 12.4731662804362 | umid_min |      62 | A90   | Awi       | NA      |          | SBSV              | SBAR

```

**Comment by esloch** [comment]
@claudia-codeco and @viniciusbgodinho, the climatic variables between the *"Dengue_global"."parameters"*  and *"Municipio"."Historico_alerta"* tables do not match for geocode **2926004** :
**[umid.min] != [umid.max]**
![values_dont_match_SBPL_2926004_20220329_155118](https://user-images.githubusercontent.com/3450741/160686221-cd272aeb-3d8c-426f-a4b4-efb6f1c1603c.png)

**Comment by viniciusbgodinho** [comment]
@esloch os valores serão completados quando entrar todas as variáveis na tabela histórico([#506](https://github.com/AlertaDengue/AlertaDengue/issues/506)) , dessa forma poderia puxar a variável climática correspondente para cada município?

``` 
> comando2 <- "SELECT \"SE\", municipio_geocodigo, tempmin, tempmed, tempmax, umidmin, umidmed, umidmax
+ FROM \"Municipio\".\"Historico_alerta\" WHERE   municipio_geocodigo = 2926004"
> dd2 <- dbGetQuery(con, comando2)
> tail(dd2)
        SE municipio_geocodigo  tempmin  tempmed  tempmax  umidmin  umidmed  umidmax
629 202203             2926004 23.57143 26.98320 31.85714 47.45794 69.00793 87.54513
630 202204             2926004 22.57143 25.54564 30.42857 54.95747 78.23996 94.34606
631 202205             2926004 23.42857 27.25680 32.57143 46.42253 71.98999 92.19250
632 202206             2926004 23.50000 27.31250 32.33333 48.68343 69.25960 85.29882
633 202207             2926004 23.00000 24.81945 28.50000 69.45170 88.72570 97.07430
634 202208             2926004 24.00000 28.04170 34.00000 41.26770 62.70550 78.63990
```
Mas assim iria variar as variáveis climáticas para cada município, ficaria meio estranho o gráfico sem padrão, né?

@claudia-codeco seria possível definir os valores críticos na tabela *"Dengue_global"."parameters"*  para essas seis variáveis climáticas (*tempmin, tempmed ,tempmax ,umidmin, umidmed, umidmax*) ?

**Comment by esloch** [comment]
> @esloch os valores serão completados quando entrar todas as variáveis na tabela histórico(https://github.com/AlertaDengue/AlertaDengue/issues/506) , dessa forma poderia puxar a variável climática correspondente para cada município?  

Os dados para o novo gráfico_climático e a visualização da tabela na página do relatório municipal são determinados por **varcli** e **varcli2** da *RegionalParameters*, caso tenha essa segunda variável para o município:
![parameters_remanso_ba_20220330_072951](https://user-images.githubusercontent.com/3450741/160811623-422a2e7a-14fa-4b5b-bf99-a830014e520a.png)

#### geocode=2911907 #umid.max | Iaço BA:
![chart_20220330_073923](https://user-images.githubusercontent.com/3450741/160813262-00354f69-70cc-4c77-88c0-217dd7efcc11.png)

![df_table_20220330_073721](https://user-images.githubusercontent.com/3450741/160813051-d9a887d1-85a0-4699-91a2-52b376fb4a0c.png)

**Comment by claudia-codeco** [comment]
a varcli2 por enquanto só existe para alguns municipios, mas estou me
organizando para colocar em todos. Entao se nao tiver, considere como NULL
mesmo, por enquanto.

**Comment by esloch** [comment]
> a varcli2 por enquanto só existe para alguns municipios, mas estou me organizando para colocar em todos. Entao se nao tiver, considere como NULL mesmo, por enquanto.  

Isso mesmo @claudia-codeco , os municípios que não tem a varcli2 na tabela "RegionalParameters" são tratados como **None**.
Exemplo **RJ 3304557**... então nesse caso no gráfico e na tabela(html) será mostrado apenas a *varcli(clicrit)*:
![isnone_parameters_rj_20220330_181717](https://user-images.githubusercontent.com/3450741/160932489-9a01c7b2-e4e9-4fc9-84f5-fd028ac38f13.png)
![3304557_climate_chart_20220330_182301](https://user-images.githubusercontent.com/3450741/160933325-2990d1b3-66d2-4391-b6e2-f8b67ca8a1ed.png)
![3304557table_df_html](https://user-images.githubusercontent.com/3450741/160933759-e21b2cd9-6d4d-4d98-bbbe-bcb6e44fd2fd.png)

**Comment by esloch** [comment]
> Mas assim iria variar as variáveis climáticas para cada município, ficaria meio estranho o gráfico sem padrão, né?  

Essa variação corresponderá as variáveis definidas na *RegionalParameters* para cada geocode. Os gráficos estão flexibilizados de momento para mostrar apenas uma ou duas variáveis.  
> ...os valores serão completados quando entrar todas as variáveis na tabela histórico(https://github.com/AlertaDengue/AlertaDengue/issues/506) , dessa forma poderia puxar a variável climática correspondente para cada município?  

Isso mesmo @viniciusbgodinho, ao preencher todos os campos das variáveis climáticas na tabela *historico_alerta*, um ou outro irá corresponder a **varcli**, ou **varcli2** na *RegionalParameters*, e assim mostrará os dados corretamente.

Os novos atributos para as variáveis climáticas já foram inseridos na *historico_alerta*: 
``` 
umidmin
umidmed
tempmed
tempmax 
``` 
Qual é o próximo passo para gerar o script e atualizar todos os campos da tabela *historico_alerta* da produção?

**Comment by claudia-codeco** [comment]
Está comigo esse passo. Vou finalizar isso o mais rapido possivel
