### ISSUE TITLE
Atualizar página participe

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#438]
# Objetivos / Objectivos / Purpose

## Geral / General

* Atualizar o conteudo da página participe:
https://info.dengue.mat.br/participe/

## Específicos / Specific

* Modificar o texto e inserir imagens de acordo ao documento:
[como participar.docx](https://github.com/AlertaDengue/AlertaDengue/files/6725112/como.participar.docx)

# Justificativa / Justification

* Facilitar o acesso ao conteúdo do site e de como participar no infodengue.

**Comment by esloch** [comment]
![new_page](https://user-images.githubusercontent.com/3450741/124310913-47461880-db43-11eb-9cd5-d22fcd9b299b.png)
![select_city](https://user-images.githubusercontent.com/3450741/124310918-48774580-db43-11eb-8142-ee730b270926.png)
![report_type](https://user-images.githubusercontent.com/3450741/124310919-48774580-db43-11eb-9c70-1da41e497333.png)
![search_city](https://user-images.githubusercontent.com/3450741/124310920-490fdc00-db43-11eb-842d-812e82588b8e.png)

**Comment by esloch** [comment]
Textos e telas propostas:
[como_participar.docx](https://github.com/AlertaDengue/AlertaDengue/files/6756202/como_participar.docx)

**Comment by lsbastos** [comment]
Oi Sandro, qdo tiver um tempinho pra atualizar meu nome no site. (Leonardo S Bastos) Meu sobrenome é Soares e nao Souza, mas pode deixar só o S.
