### ISSUE TITLE
check if the time series in the first page is been updated correctly

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#44]

**Comment by fccoelho** [comment]
@claudia-codeco 

esta consulta deve ser executada sempre depois que a tabela do Historico_alerta for modificada.

REFRESH MATERIALIZED VIEW uf_total_view AS SELECT uf, "data_iniSE" AS data, sum(casos) casos_s, sum(casos_est) casos_est_s FROM
"Municipio"."Historico_alerta" INNER JOIN "Dengue_global"."Municipio" 
on "Historico_alerta".municipio_geocodigo="Municipio".geocodigo  
GROUP BY "data_iniSE", uf ORDER BY uf, "data_iniSE" ASC;

**Comment by fccoelho** [comment]
@flavioamieiro can you put this in a cron script to avoid this happening again?

**Comment by fccoelho** [comment]
Sorry the previous query is wrong. The correct one is simply

```sql
refresh materialized view uf_total_view
```
