### ISSUE TITLE
Atualizar página da equipe

### ISSUE THREAD

**Issue by lsbastos** [AlertaDengue/AlertaDengue#440]
# Objetivos / Objectivos / Purpose

## Geral / General

* Correção de sobrenome na pagina da equipe no site do infodengue. 

## Específicos / Specific

* Trocar Souza por Soares. O nome certo é Leonardo Soares Bastos

# Justificativa / Justification

* Sobrenome errado

**Comment by sarasouzabh** [comment]
Modifiquei o nome da issue ,caso haja algum outro problema.

**Comment by claudia-codeco** [comment]
Sim, temos as seguintes alterações:

**Remover:**
Elton Nogueira Santana: Full Stack TI 
Beatriz Macedo Coimbra: Aluna de graduação do Programa de Matemática Aplicada da FGV e PIBIC da Fiocruz 
Lucas Monteiro Bianchi: Aluno de doutorado do Programa de Epidemiologia em Saúde Pública - ENSP/Fiocruz 

**Modificar:**
Iasmim Ferreira de Almeida: Aluna de doutorado do Programa de Epidemiologia em Saúde Pública - ENSP/Fiocruz

**Acrescentar Alunos:**
 Nathaly Dutra, Aluna de mestrado do Programa de Epidemiologia em Saúde Pública - ENSP/Fiocruz 

**Acrescentar Parceria:**
Secretaria Municipal de Saúde de Rio Branco/AC
Secretaria de Vigilância em Saúde/MS
