### ISSUE TITLE
Resposta da API  quando Estado não tem dados atualizados

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#451]
Atualmente a API consumida pelo aplicativo androide Infodengue, retorna as últimas duas semanas da série da cidade quando os parâmetros de semanas de início e fim não são especificados.

Entretanto, quando a série da cidade não chega até a semana atual ela retorna uma resposta vazia. Este comportamento faz com que o aplicativo não tenha informações para apresentar para uma cidade, quando, na verdade, deveria mostrar a última informação disponível.

O comportamento padrão da API deve ser modificado para sempre retornar as duas últimas semanas disponíveis quando as semanas de início e fim não são especificadas na requisição.

**Comment by viniciusbgodinho** [comment]
Pra não misturar os códigos criei essa nova issue para o R, https://github.com/AlertaDengue/AlertaDengue/issues/453
