### ISSUE TITLE
Atualizar o APP de upload de DBFs para aceitar DBFs do Brasil

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#452]
Atualmente o formulário de upload de DBFs, requer a especificação do estado a que se refere o DBF. Porém, agora que o Infodengue recebe DBF de todo o país, podemos remover este campo ou permitir a entrada `BR` caso seja útil.

Outra falha é que na rotina de validação  do modelo de dados o processo falha se o campo `NM_BAIRRO` não existe. Este erro deve ser convertido em um simples warning, pois o DBF nacional não o contém.
> BR-CHIK-2021-08-23-2021.dbf
![nm_bairro](https://user-images.githubusercontent.com/3450741/130622033-494f5a5b-636e-43f2-ab33-125806f9a6d3.png)

**Comment by esloch** [comment]
> Atualmente o formulário de upload de DBFs, requer a especificação do estado a que se refere o DBF. Porém, agora que o Infodengue recebe DBF de todo o país, podemos remover este campo ou permitir a entrada `BR` caso seja útil.
- Conversando com @sarasouzabh ainda seguirão sendo feito os uploads por estados, apenas o campo do formulário é para ser removido?
> Outra falha é que na rotina de validação do modelo de dados o processo falha se o campo `NM_BAIRRO` não existe. Este erro deve ser convertido em um simples warning, pois o DBF nacional não o contém.
- Olhando por cima... Para a validação dos campos usamos o validation.py que [espera](https://github.com/AlertaDengue/AlertaDengue/blob/main/AlertaDengue/dbf/validation.py#L10) os campos especificados e retorna a mensagem a baixo caso não encontre. Algum DBF como referência para testes? 
```
raise ValidationError(
{
    "__all__": _(
        "Este arquivo "
        "não contém {}, que é esperado em um arquivo "
        "válido do SINAN.".format(field)`
    )
}
```
Temos algum traceback?

**Comment by sarasouzabh** [comment]
@esloch Acho que o caminho é acrescentar na lista de estados, o Brasil. Acho que o que o Flavio quer dizer é atualmente a escolha de um estado é obrigatória. E quando enviamos os dados do Brasil não existe a opção de ignorar o estado ou de colocar "Brasil". 

Certo @fccoelho ?

**Comment by fccoelho** [comment]
certo @sarasouzabh .

**Comment by esloch** [comment]
Registrando o log dos uploads no staging de 3 arquivos DBFs Nacionais (chik, dengue e zika). Apenas o de ZIKA_SE28 concluiu o upload:

> BR_CHIK_SE30_2021.dbf
```
staging_web_1            | Instanciando SINAN (/MEDIA_ROOT/BR_CHIK_SE30_2021.dbf, 2021)
staging_web_1            | Formatando as datas
staging_web_1            | Escrevendo no PostgreSQL
staging_web_1            | Formatando linhas e inserindo em "Municipio"."Notificacao"
staging_web_1            | 1000 linhas inseridas. Commitando mudanças no banco
.......
staging_web_1            | 59000 linhas inseridas. Commitando mudanças no banco
staging_web_1            | [2021-08-24 12:38:23 +0000] [82] [CRITICAL] WORKER TIMEOUT (pid:393)
staging_web_1            | [2021-08-24 12:38:23 +0000] [393] [INFO] Worker exiting (pid: 393)
staging_web_1            | [2021-08-24 12:38:24 +0000] [82] [WARNING] Worker with pid 393 was terminated due to signal 9
staging_web_1            | [2021-08-24 12:38:24 +0000] [442] [INFO] Booting worker with pid: 442
```
> Dengue_SE30.dbf
```
staging_web_1            | Instanciando SINAN (/MEDIA_ROOT/Dengue_SE30.dbf, 2021)
staging_web_1            | [2021-08-24 12:10:51 +0000] [82] [CRITICAL] WORKER TIMEOUT (pid:112)
staging_web_1            | [2021-08-24 12:10:54 +0000] [82] [WARNING] Worker with pid 112 was terminated due to signal 9
staging_web_1            | [2021-08-24 12:10:54 +0000] [383] [INFO] Booting worker with pid: 383
staging_web_1            | Not Found: /favicon.ico
staging_web_1            | Instanciando SINAN (/MEDIA_ROOT/Dengue_SE30_aJrpUtJ.dbf, 2021)
ddstaging_web_1            | [2021-08-24 12:15:53 +0000] [82] [CRITICAL] WORKER TIMEOUT (pid:110)
staging_web_1            | [2021-08-24 12:15:54 +0000] [82] [WARNING] Worker with pid 110 was terminated due to signal 9
staging_web_1            | [2021-08-24 12:15:54 +0000] [393] [INFO] Booting worker with pid: 393
``` 
> BR_ZIKA_SE28_2021.dbf 
``` 
staging_web_1            | Instanciando SINAN (/MEDIA_ROOT/BR_ZIKA_SE28_2021.dbf, 2021)
staging_web_1            | Formatando as datas
staging_web_1            | Escrevendo no PostgreSQL
staging_web_1            | Formatando linhas e inserindo em "Municipio"."Notificacao"
staging_web_1            | 1000 linhas inseridas. Commitando mudanças no banco
staging_web_1            | 2000 linhas inseridas. Commitando mudanças no banco
staging_web_1            | 3000 linhas inseridas. Commitando mudanças no banco
staging_web_1            | 4000 linhas inseridas. Commitando mudanças no banco
staging_web_1            | 5000 linhas inseridas. Commitando mudanças no banco
staging_web_1            | 6000 linhas inseridas. Commitando mudanças no banco
staging_web_1            | 7000 linhas inseridas. Commitando mudanças no banco
staging_web_1            | 8000 linhas inseridas. Commitando mudanças no banco
staging_web_1            | Sinan <unloaded DBF table '/MEDIA_ROOT/BR_ZIKA_SE28_2021.dbf'> inserido no banco
staging_web_1            | Task dbf.tasks.import_dbf_to_database[5488ef3c-422f-44c8-9b45-e02d7efa1c96] succeeded in 78.3318589180708s: None

O arquivo BR_ZIKA_SE28_2021.dbf exportado em 24/03/2021 com notificações do ano 2021 foi enviado com sucesso. Você será informado por email (alerta_dengue@fiocruz.br) assim que o processo de importação for finalizado,
```
