### ISSUE TITLE
Incluir variaveis novas na tabela Municipio.Notificacao para permitir calculos solicitados pelo MS

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#467]
# Justificativa
Para calcular indicadores solicitados pelo Ministerio da Saude, precisamos criar variaveis novas na tabela Municipio.Notificacao.  

As variaveis são : 
CLASSI_FIN  numérica
CRITERIO numérico
RESUL_PCR  numerico 

Todas devem permitir dados faltantes. 

Uma vez isso feito, precisaremos abrir uma issue no AlertaDengueCaptura para passar a capturar essas variaveis dos dbfs que recebemos

**Comment by esloch** [comment]
@claudia-codeco não entendi sobre a issue dos dbfs, podes detalhar?
O upload dos dbfs com os dados do SINAN feito no admin do site são inseridos diretamente na tabela Municipio.Notificacao.
