### ISSUE TITLE
Modificar o texto do "Sobre o Infodengue". 

### ISSUE THREAD

**Issue by sarasouzabh** [AlertaDengue/AlertaDengue#504]
### Geral / General

* Objetivo da solicitação / Objectivo de la solicutud / Purpose of the request

### Específicos / Specific

* Funcionalidades [desejadas / deseadas] / Desired functionalities

### Justificativa / Justification

* Problemas que se pretende resolver / Problems that are to be solved

**Comment by MarcelleChagas** [comment]
**Modificação de texto no site aprovado** 

Alterações no site
Etapa 1
Sobre o InfoDengue

O InfoDengue é um sistema de alerta para arboviroses baseado em dados híbridos gerados por meio da análise integrada de dados minerados a partir da web social e de dados climáticos e epidemiológicos.

Em 2021, o sistema ganhou amplitude nacional com o apoio do Ministério da Saúde realizando análises em nível estadual. Com isso, mais secretarias passaram a receber semanalmente os boletins do InfoDengue. Implementado em 2015, o sistema foi desenvolvido por pesquisadores do Programa de Computação Científica (Fundação Oswaldo Cruz, RJ) e da Escola de Matemática Aplicada (Fundação Getúlio Vargas) com a forte colaboração da Secretaria Municipal de Saúde do Rio de Janeiro, o Observatório da Dengue/UFMG e pesquisadores da Universidade Federal do Paraná e da Universidade Estadual do Oeste do Paraná.

Embora desenvolva boletins com análises de casos de dengue, zika e chikungunya de todo o país, os estados ainda podem aderir ao sistema.  Acesse o [como participar](https://info.dengue.mat.br/participe/) para integrar o InfoDengue. O estado participante recebe um relatório de análise de situação da dengue semanalmente. A versão pública do site é acessada por muitas pessoas e é comum recebermos notícias de que essas informações são utilizadas na definição de viagens e outras atividades.

Nossa rede de colaboradores cresceu e conta agora com a parceria de grupos de pesquisa internacionais que buscam soluções para arboviroses em outros países e organizações da sociedade civil. Por meio do compartilhamento de experiências e metodologias, ampliamos a inovação e o conhecimento das arboviroses.

Vários desafios técnicos e científicos foram enfrentados durante o desenvolvimento do InfoDengue, resultando em diversas teses e dissertações. Como os desafios não terminam, continuamos e continuaremos sempre investigando novas soluções para gerar informação útil para a gestão  e para o avanço do conhecimento das arboviroses e seu controle.


@sarasouzabh @esloch

**Comment by esloch** [comment]
@claudia-codeco, você pode corrigir o texto em inglês?
Essa mesma versão já está em: https://infostaging.dengue.mat.br/informacoes/

>InfoDengue is an alert system for arboviroses based on the continuous analysis of online, climate and epidemiological data..

>In 2021, the system gained national breadth with the support of the Brazilian Health Ministry performing analysis at the state level. As a result, more Health Department began to receive weekly InfoDengue bulletins. Implemented in 2015, the system was developed by researchers from the Scientific Computing Program(Fundação Oswaldo Cruz, RJ) and the School of Applied Mathematics (Fundação Getúlio Vargas) with the strong collaboration of the Rio de Janeiro Municipal Health Secretariat,the Observatory of Dengue (UFMG) and researchers from the Federal University of Paraná and the State University of Western Paraná.

>Although it develops bulletins with analyzes of dengue, zika and chikungunya cases from across the country, states can still join the system. Access how to participate to integrate InfoDengue. The participating state receives a weekly dengue status analysis report. The public version of the site is accessed by many people and it is common for us to receive news that this information is used in the definition of travel and other activities.

>Our network of collaborators has grown and now includes international research groupsseeking solutions for arboviruses in other countries and civil society organizations. By sharing experiences and methodologies, we expand innovation and knowledge of arboviruses.

>Several technical and scientific challenges were faced during the development of InfoDengue, resulting in several theses and dissertations. As the challenges do not end, we continue and will always continue to investigate new solutions to generate useful information for the management and advancement of knowledge of arboviruses and their control.

**Comment by claudia-codeco** [comment]
InfoDengue is an early warning system for arbovirosis in Brazil. It relies on the continuous analysis of online, climate and epidemiological data. In 2021, the system reached the national level with the support of the Brazilian Health Ministry. As a result, all municipalities began to receive weekly InfoDengue bulletins. 
Reports at the state level can be requested by the state health secretariats. Access the tab “how to participate” to know more.
Implemented in 2015, the system was developed by researchers from the Scientific Computing Program(Fundação Oswaldo Cruz, RJ) and the School of Applied Mathematics (Fundação Getúlio Vargas) with the strong collaboration of the Rio de Janeiro Municipal Health Secretariat,the Observatory of Dengue (UFMG) and researchers from the Federal University of Paraná and the State University of Western Paraná. The Infodengue website is accessed by many people and it is common for us to receive news that this information is used in the definition of travel and other activities.
Our network of collaborators has grown and now includes international research groups seeking solutions for arboviruses in other countries and civil society organizations. By sharing experiences and methodologies, we expand our capacity to innovate on arbovirus surveillance.
The several technical and scientific challenges faced during the development of InfoDengue resulted in theses and dissertations. As the challenges do not end, we continue and will always continue to investigate new solutions to generate useful information for the management and advancement of knowledge of arboviruses and their control.
