### ISSUE TITLE
Enhance Performance of City Search in Menubar Textbox

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#510]
This issue focuses on optimizing the performance of the city search functionality in the menubar textbox. Currently, there might be performance issues when searching for cities, leading to delays or slow response times.

### Improve performance of city search function and remove unnecessary code:
[get_city()](https://github.com/AlertaDengue/AlertaDengue/blob/main/AlertaDengue/dados/dbdata.py#L450)

The usage of JOIN operations in the query is leading to noticeable degradation in performance, which directly impacts the overall execution speed.

This issue arises due to the involvement of a large table named "historico_alerta," resulting in a significant slowdown in query execution.

To address this performance concern, it is highly recommended to consider alternative approaches. One potential solution is leveraging a dictionary or a JSON file that contains pre-processed data of all municipalities per state. By adopting this approach, the retrieval of the required information can be expedited, leading to improved query performance.

Another effective strategy to enhance the overall result is implementing a caching mechanism like Memcache. By utilizing Memcache, the application can store frequently accessed data, resulting in improved performance and reduced database load.

If the primary objective is solely to retrieve city names based on the state, it is worth exploring these alternative solutions, as they have the potential to optimize the query execution and mitigate performance issues.

Furthermore, it is crucial to evaluate the role and functionality of the JavaScript code. It is important to determine if the code serves any essential purpose or if it can be safely removed. Conducting this evaluation will contribute to maintaining a cleaner and more efficient codebase by eliminating any unnecessary components.

*Another way to improve would be to reuse the code for searching municipalities in the [API](https://github.com/AlertaDengue/AlertaDengue/blob/main/AlertaDengue/dados/templates/services_api.html#L100).*
![Screenshot_20230518_073023](https://github.com/AlertaDengue/AlertaDengue/assets/3450741/d5dac20f-beeb-47ab-864b-3d51a090811b)

**Comment by luabida** [comment]
search menu bar is located at Alertadengue/dados/templates/services_api.html wrote in JS.
