### ISSUE TITLE
Criar entradas nas tabelas para registrar casos provaveis das doencas 

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengue#527]
# Objetivos / Objectivos / Purpose

Para atender demanda do MS, vamos incluir entradas nas tabelas de historico para registrar o numero casos provaveis. 

# Entradas / Input

Incluir nas tabelas
-  historico_alerta
- historico_alerta_chik
- historico_alerta_zika

As variaveis
casprov  , com mesma especificacao de tipo de `casos`
casprov_est, com mesma especificacao de tipo de `casos_est`
casprov_est_min, com mesma especificacao de tipo de `casos_est_min`
casprov_est_max, com mesma especificacao de tipo de `casos_est_max`
casconf  , com mesma especificacao de tipo de `casos`

**Comment by esloch** [comment]
@claudia-codeco, talvez colocar os nomes dos campos usando o mesmo padrão; aqui é importante legibilidade,
exemplo:
> casprov_est_max --> casos_prov_est_max

Não precisamos economizar caracteres para isso :)

Teremos mais algum outro campo além dos que já foram listados acima?
