### ISSUE TITLE
Error loading epiweek on alert page for city of Rio de Janeiro

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#541]
# Objetivos / Objectivos / Purpose

## Geral / General

![SE_ERROR_2022_20220630_075413](https://user-images.githubusercontent.com/3450741/176660702-95672351-b45e-4b0f-b934-22c287d382df.png)

**Comment by esloch** [comment]
Missed removing MRJ from API tests:
>from ..db import MRJ_GEOCODE

[test_views](https://github.com/AlertaDengue/AlertaDengue/blob/main/AlertaDengue/api/tests/test_views.py#L12)
ping @luabida.

**Comment by luabida** [comment]
@esloch good catch! Are the tests failing? I think they should accept Rio's geocode as normally, same to any other geocode. This afternoon I'll run these tests with different geocodes and see if there is need for changing to a different geocode or add a couple more. Thank you
