### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#55]
@fccoelho @flavioamieiro 

Com a nova funcionalidade da página de alertas por estado, onde a cada alteração de filtro será atualizada a página, percebe-se que o transmissão de dados será intensa. por exemplo na visualização por Paraná é baixado em torno de 5 MB a cada requisição.

Fiz um teste gravando os json em arquivos .json e deixando dentro de static ... e teve um resultado positivo. A primeira vez que carrega ele já é mais rápido que a versão anterior. E na segunda vez ele já está cacheado no navegador (caindo para 500KB).

Tentei fazer só por:

```python

response = HttpResponse(geojson_city)
response['Cache-Control'] = 'max-age=0'
return response

```

Porém não funcionou. Não sei se é possível fazer isso.

Pensei que talvez poderia ser feito uma rotina na inicialização do aplicativo, onde ele verificaria se foi criado o json de cada cidade dentro de static, e em caso negativo, poderia criá-lo. Assim não seria necessário adicionar esses arquivos no github.

Poderia também ser feito testes com arquivos json para todo o estado. Com relação a pegar esses dados do django, penso que da diferença, pois além do tempo de execução dentro da aplicação, tem ainda o tempo que leva nas verificações do protocolo. Cacheando no cliente não sei se tem vantagem.

O que vocês opinam?

**Comment by flavioamieiro** [comment]
@xmnlab eu acho uma boa ideia a gente gerar esses arquivos e colocar no lugar dos staticfiles pra eles não precisarem ser gerados sempre. 

Minha sugestão é [escrever um management command](https://docs.djangoproject.com/en/1.10/howto/custom-management-commands/) pra isso. Assim a gente pode rodar algo como `python manage.py generate_state_json` (com um nome melhor, por favor :p) e isso também fica acessível diretamente pelo código, dentro da aplicação. Minha idéia é que com esse management command, a gente pode gerar esses arquivos na hora de fazer o deploy (com o `manage.py`) e também diretamente de dentro da aplicação depois de cada importação, se isso for necessário (caso os arquivos mudem com os dados novos).

Sobre o cache: pelo que eu entendo definir o `Cache-Control` com `"max-age=0"` diz para o navegador que aquele arquivo está defasado e o navegador não deve usar o cache que ele tem. Por isso que ele tá fazendo a requisição novamente quando vem esse header. Com certeza temos como fazer esse cache no navegador ser mais esperto. A seção de [downstream caches](https://docs.djangoproject.com/en/1.9/topics/cache/#downstream-caches) da documentação do django é bem boa, acho que nosso caso de uso vai estar ali. A gente também pode definir um tempo de cache (grande) para todos os arquivos estáticos diretamente no servidor web (o nginx que fica antes do request chegar na aplicação). Se a gente definir lá um `Cache-Control` que faça sentido para todos os arquivos estáticos a gente não precisa se preocupar com isso na aplicação (só precisamos ter cuidado pra esse tempo não ser grande demais para alguns arquivos).

**Comment by xmnlab** [comment]
@flavioamieiro Ok! vou trabalhar nisso! muito agradecido!
