### ISSUE TITLE
Django Debugger

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#62]
@fccoelho @flavioamieiro 

O django tem debbuger interativo semelhante ao do flask (werkzeug)?

Acho que para debugar é bem interessante ter um debugger interativo nesse estilo.

Eu fiz um teste usando o django-extentions junto com o werkzeug e funcionou bem:

https://spapas.github.io/2016/06/07/django-werkzeug-debugger/

para não correr o risco de afetar nada em produção estou incluindo-o assim:

```python

if DEBUG:
    INSTALLED_APPS += ('django_extensions',)
```

Vocês tem outra sugestão?

**Comment by fccoelho** [comment]
Tem a Django-debug toolbar, que já usamos. Não sei como se compara com a
funcionalidade do flask.

Em 9 de fev de 2017 11:20, "Ivan" <notifications@github.com> escreveu:

**Comment by xmnlab** [comment]
é possível inserir códigos durante a depuração?

**Comment by flavioamieiro** [comment]
@xmnlab Eu geralmente uso o ipdb, e uso o terminal onde esta rodando o servidor de desenvolvimento para interagir com ele.

A princípio eu não tenho problema nenhum com a adição dessa extensão se o DEBUG estiver ligado.

**Comment by xmnlab** [comment]
OK! e a principio ele só funciona se for chamada assim:

```sh

python manage.py runserver_plus

```

subi no branch develop

qq coisa me avisem e eu tiro.

**Comment by xmnlab** [comment]
vou deixar as libs no requirements-dev.txt e vou deixar para adicionar isso pelo local_settings.py .. assim fica algo opcional:

```python

INSTALLED_APPS += ('django_extensions',)

```
