### ISSUE TITLE
Erro 502  no DBF upload

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengue#69]
@flavioamieiro A URL está dando erro 502 logo após o login.

**Comment by flavioamieiro** [comment]
A configuração do postgres do servidor de produção não estava permitindo acesso ao banco usado pela aplicação django (apesar de estar permitindo acesso ao banco com os dados de casos). Já corrigi a configuração e reiniciei o serviço, tudo parece estar funcionando.
