### ISSUE TITLE
Ajuste no sistema para trabalhar com Historico_alerta para todas as doenças

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#74]
@fccoelho @flavioamieiro 

Devido à inclusão da chikungunya no sistema gostaria de saber de vocês o que vocês acham sobre o tema.

Na tela principal nos cards, eu estava utilizando já os dados processados na Historico_alerta.

Eu vejo duas opções: 

1) utilizar a tabela Notificacao e somar os casos apresentados para todas as doenças dentro do periodo analisado.

2) fazer uma view para somar os casos já processados na Historico_alerta e Historico_alerta_chik.

Até o momento vi a necessidade apenas de somar os casos* apresentados na tabela Historico_alerta, então só incluí esses campos na view:

```sql

SELECT 
    dengue."data_iniSE",
    dengue."SE",
    dengue.casos_est + chik.casos_est AS casos_est,
    dengue.casos_est_min + chik.casos_est_min AS casos_est_min,
    dengue.casos_est_max + chik.casos_est_max AS casos_est_max,
    dengue.casos + chik.casos AS casos,
    dengue.municipio_geocodigo
FROM 
    "Municipio"."Historico_alerta" AS dengue
    INNER JOIN "Municipio"."Historico_alerta_chik" AS chik
        ON dengue."SE" = chik."SE"
	    AND dengue.municipio_geocodigo = chik.municipio_geocodigo

```

o que vocês acham?

**Comment by xmnlab** [comment]
**ops deveria ser um LEFT JOIN

**Comment by flavioamieiro** [comment]
Eu acho uma boa ideia fazer a view, já que a query não vai (teoricamente) mudar. Em um outro caso, nós fizemos uma materialized view, que deixa tudo pré-calculado, mas não sei se se aplica a esse caso.

**Comment by xmnlab** [comment]
@flavioamieiro 

dentro da pasta sql foi incluído o arquivo create_historico_casos.sql,para ser incluído quando for feita a migração do develop para o master.
