### ISSUE TITLE
Agendar update da view uf_total_chik_view

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#78]
> Além disso, precisamos agendar o update da view, como fazemos com a outra materialized view que temos.

**Comment by flavioamieiro** [comment]
@xmnlab se quiser, é só me dizer qual a query que tem que tem que ser executada que eu coloco ela pra rodar no crontab junto com a que atualiza a materialized view de total por UF.

**Comment by xmnlab** [comment]
no fim do dia vou dar um PR e te informo aqui o que tem que ser agendado :)

agradecido!

**Comment by xmnlab** [comment]
@flavioamieiro 

na raiz do projeto foi criado uma pasta chamada sql (depois se quiserem trocar, fiquem a vontade) e foi criado um script chamado create_uf_total_chik_view.sql

quando foi pro master ai vai precisar executar esse script.

se quiser dar uma revisada também fique a vontade :)

**Comment by flavioamieiro** [comment]
@xmnlab eu vi o comentário na outra issue antes. Dei uma olhada já, e parece tudo certinho. Para a outra view, no cron, nós usamos o [`REFRES MATERIALIZED VIEW`](https://www.postgresql.org/docs/9.6/static/sql-refreshmaterializedview.html) para atualizar, mas talvez seja melhor rodar o sql completo. Vou deixar essa issue aberta (mudei o asignee pra mim) pra quando fizermos o merge eu atualizar a crontab no servidor.

**Comment by fccoelho** [comment]
Só um comentário: estamos tentando obter os dados para as demais cidades do RJ, mas por enquanto só temos os dados de Chikungunya para a capital.

**Comment by flavioamieiro** [comment]
@xmnlab já adicionei a atualização dessa view no cron. Usei a solução com `REFRESH MATERIALIZED VIEW` por que o `CREATE` falha quando a view já existe.
