### ISSUE TITLE
Incluir campo de última atualização na visualização por estados

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#81]
Complemento da issue #47.

> Adicionar logo abaixo do nome do estado, a data da ultima atualização de dados. pois isto varia de estado para estado.
> Enquanto isso @xmnlab , pode preparar o código para ler a última data da tabela de uploads, com um fallback de dizer "unknown" enquanto não tivermos as datas sendo atualizadas regularmente nesta tabela.
> 
> basta entrar em https://info.dengue.mat.br/dbf/upload/ (tem que ter um usuário cadastrado lá) e preencher o formulário. Assim que a barra de progresso do envio estiver completa (e todos os campos do formulário preenchido), o botão de enviar passa a estar habilitado, e aí basta clicar em enviar. A aplicação vai fazer a importação fora do ciclo de request/response, mas quando a importação estiver pronta, o usuário vai receber um e-mail (com o endereço que tá cadastrado para o usuário) informando o status da importação.
> 
> A data do dbf que nós registramos é informada pelo usuário (no campo "data da exportação" no formulário).
> 
>@xmnlab Eu não sei exatamente qual o campo da tabela no banco, mas já que estamos usando código da aplicação, é bem melhor usar os Models do django para acessar os atributos. Nesse caso, o código abaixo resolveria:
>
> from dbf.models import DBF                    
> DBF.objects.order_by('export_date').last()
> 
> A API de queryset tem várias outras maneiras úteis de usar os models. Assim o código fica muito mais legível e as queries em geral ficam bem mais eficientes.

**Comment by xmnlab** [comment]
@flavioamieiro 

por algum motivo parece que o model DBF  está desvinculado da tabela dbf_dbf. Utilizando o código:

```python

from dbf.models import DBF
DBF.objects.order_by('export_date').last()

```

me retorna None

Também parece que o migrate que foi executado (com sucesso) porém não alterou a tabela dfb_dbf.

Tens alguma ideia?

**Comment by flavioamieiro** [comment]
@xmnlab aqui na minha máquina, rodando com o último dump de dev (2017-03-03_infodengue.sql e 2017-03-03_infodengue.sql) o resultado é:

```
In [1]: from dbf.models import DBF

In [2]: DBF.objects.order_by('export_date').last()
Out[2]: <DBF: MRJdengon2017-09-01-2017_f2UCmMX.dbf - 2017>
```

Lembrando que usamos dois bancos (por isso os dev_dumps vem em pares): o `dengue` é usado por várias aplicações diferentes (inclusive essa aplicação django) para guardar e recuperar os dados sobre casos, etc. O `infodengue` (esse nome é o padrão, mas pode ser modificado se quiser) é um banco que só essa aplicação django usa, que usa o ORM do django. Quando a gente roda `DBF.objects.order_by('export_date').last()` é no banco `infodengue` que o ORM do django vai buscar os dados. 

Por isso, você precisa desse banco carregado. Ou rodando `python manage.py migrate` (pra criar as tabelas) e depois importando um DBF (para popular essa tabela) ou importando o dev_dump correspondente (que já tem alguns usuários e alguns dados nessa tabela).

**Comment by xmnlab** [comment]
@flavioamieiro 

Estou tendo problemas também com outras tabelas .. por exemplo, a tabela de usuários do django rsrs

talvez deve ser algum problema de settings .. talvez esteja criando outra base de dados.

vou verificar aqui e te falo.

**Comment by xmnlab** [comment]
@flavioamieiro 

pelo que vi está indo para o geodjango.db 

possivelmente por causa da configuração:

```python

'default': config('DATABASE_URL', default='sqlite:///geodjango.db', cast=db_url)

```

Deve usar mesmo o sqlite? ou teria que usar o postgresql?

**Comment by flavioamieiro** [comment]
Foi mal @xmnlab, eu esqueci que a configuração padrão era essa. Aqui na minha máquina eu coloco no arquivo de configurações local (`settings.ini` ou `.env`) a seguinte linha: 

`DATABASE_URL=postgres://usuario:senha@localhost:5432/infodengue`

Você pode fazer o mesmo, apontar o banco pra um postgres na sua máquina com o dump carregado ou continuar usando o sqlite, rodar as migrações e enviar um dbf (e criar usuários). Fica a seu critério. Pra aplicação django em um ambiente de desenvolvimento faz pouquíssima diferença.

**Comment by xmnlab** [comment]
@flavioamieiro obrigado! já to rodando pelo postgresql 👍
