### ISSUE TITLE
Cidades presentes no mapa na visualização por estado

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#86]
@fccoelho @flavioamieiro 

Verifiquei aqui que a lista de cidades que é utilizada para montar o gráfico está baseada em Historico_alerta(_chik). 

Caso a cidade não estiver presente nessa tabela, não estará presente no gráfico. Em outras palavras, como ainda não tem nenhum dado ha Historico_alerta_chik, não exibirá nenhuma cidade no mapa.

**Comment by fccoelho** [comment]
Ok,

Vou acelerar a solução disso.

Em 21 de mar de 2017 18:24, "Ivan" <notifications@github.com> escreveu:
