### ISSUE TITLE
Merge from develop to master

### ISSUE THREAD

**Issue by xmnlab** [AlertaDengue/AlertaDengue#91]
@fccoelho @flavioamieiro 

Esta fase está chegando ao final. 

Gostaria de saber se vocês querem fazer alguns teste, propor ajustes, etc antes de fazer um merge no master.

além disse, vai ser necessário executar 2 itens em produção (também para fazer os testes):

1. executar o script de criação de "Municipio".historico_casos (diretório sql)
1. executar o script de criação de uf_total_chik_view  (diretório sql)
1. executar o manage.py migrate (por causa das alterações no módulo model em dbf)
1. executar o manage.py sync_geojson

Existe algum lugar para fazer um script de deploy? 

Talvez daria pra fazer um controle de versão ou algo do tipo ... poderia ser algo bem simples .. incluir um arquivo VERSION.txt fora do git .. que armazena a última versão ... e incluimos um management command do django para ver se tem algo pendente e executar.

**Comment by fccoelho** [comment]
@xmnlab , sim, seria legal fazer uns últimos testes. A tabela `alerta_mrj_chik` já está com dados, @flavioamieiro , você já pode atualizar o dump.

Script de Deploy é com o @flavioamieiro. vou deixar ele responder.

**Comment by flavioamieiro** [comment]
@xmnlab como o @fccoelho já disse, a tabela alerta_mrj_chik já está com os dados. Criei um dump de hoje que já está disponível lá.

Vou agendar no cron para que a view uf_total_chik_view seja atualizada regularmente (assim como a de dengue já é).

O deploy eu faço, pode deixar. Eu tenho usar o docker (a gente usa o [docker-compose](https://github.com/AlertaDengue/AlertaDengue/blob/master/docker-compose.yml)). Eu só preciso resolver um bug do docker na minha máquina (eu tava usando o debian unstable no meu próprio computador sem saber. Só descobri quando isso quebrou meu docker). Assim que eu resolver isso e uma outra pendência que eu tenho um pouco mais urgente (atualizar os certificados SSL de quase todos os nosso domínios) eu vou pegar essa tarefa pra fazer. 

Assim que o processo de deploy estiver pronto, vou pedir pra vocês rodarem na máquina de vocês para testar (é só um comando: `docker-compose up`) e, se estiver tudo certo, coloco no ar imediatamente.

**Comment by xmnlab** [comment]
Perfeito! Vou baixar os dumps

**Comment by flavioamieiro** [comment]
@xmnlab @fccoelho o processo de deploy não precisou de alterações. Só precisei fazer alguns commits para corrigir um erro de CSS (1440b7357 e 8376ccc), mas que não deveria trazer outros problemas.

Como a mudança foi *muito* pequena, tomei a liberdade de colocar no ar (aproveitando também que hoje é domingo). Vocês podem olhar e me dizer se está tudo ok? O deploy ainda está baseado em um branch (https://github.com/AlertaDengue/AlertaDengue/tree/new_interface), então em caso de problemas, fazer um rollback é trivial.

**Comment by xmnlab** [comment]
@flavioamieiro sigo trabalhando no develop ou melhor trabalhar no new_interface?

**Comment by flavioamieiro** [comment]
@xmnlab acho que pode seguir no develop. Só faz um merge do new_interface nele pra garantir que as mudanças que eu fiz estarão no develop. Qualquer coisa eu faço outro merge depois.

**Comment by xmnlab** [comment]
OK! ;)

**Comment by xmnlab** [comment]
@fccoelho poderias testar as issues:

#95 #101 #96 #102 #100 

qualquer problemas nessas issues pode reabrí-las.

Estou trabalhando na #103 para finalizar.

**Comment by xmnlab** [comment]
@flavioamieiro vc faz o merge pro master?

**Comment by flavioamieiro** [comment]
@xmnlab faço sim. Assim que fizer, coloco no ar.

**Comment by flavioamieiro** [comment]
@xmnlab @fccoelho Tá no ar a versão nova!

Pelo que pude ver, está tudo certinho, só tive que resolver alguns conflitos de merge. Fora isso, tudo ok! Se encontrarem algum problema, me avisem por favor.
